Separate Armor Smithy from Weapon Smithy
widelands/widelands pull request #3583
Opened 2019-11-19 19:20 UTC by kvilhaugsvik

Armor Smithy was wrongly translated as Våpensmie. Våpensmie means Weapon Smithy. This made the two buildings hard to distinguish.

2019-11-20 10:13 UTC, hessenfarmer requested changes
Widelands translation is done on transifex and only pulled in the files here. So this chanmge wouldn't be permanent. So please make an account and translate this string on transifex. We could always use translators there and would be very happy if you could find time to translate all the currently untranslated strings there (or at least some of them)

2019-11-20 11:32 UTC, kvilhaugsvik commented
I think I have changed it there too.

2019-11-20 15:38 UTC, hessenfarmer commented
If it is changed there it should go into the repo when our chieftain is pulling the translations the next time. Normally she does that weekly but at least once a month.
I think we should close this Pull request though.

2019-11-22 07:10 UTC, stonerl commented
Closing this one.

2019-11-22 07:10 UTC, closed without merging