removed return=no_stats lines as they are not needed any longer
widelands/widelands pull request #3865
Opened 2020-04-20 20:29 UTC by hessenfarmer

fixes #3863

2020-04-20 22:13 UTC, Niektory commented
Seems to work. Both the Empire Marble Mines and the Atlantean Crystal Mines run their programs in a round-robin order now.

2020-04-24 13:23 UTC, Niektory approved these changes
The changes look good.

Looking at the source the problem appears to be that `ProgramResult::kNone` is used for both "program not yet called" and "returned with no_stats" states:
https://github.com/widelands/widelands/blob/9256debc0fe6c8e00dc765d31802237a703bc6e5/src/logic/map_objects/tribes/production_program.cc#L428-L429
https://github.com/widelands/widelands/blob/9256debc0fe6c8e00dc765d31802237a703bc6e5/src/logic/map_objects/tribes/production_program.cc#L607-L609

Should we remove `return=no_stats` completely if it's bugged and not needed?

I still think Empire Marble Mine doesn't need two separate mining programs if the conditions are the same. But it doesn't need to be changed now.

2020-04-24 17:47 UTC, hessenfarmer commented
I believe I removed it totally in the lua files. But I would be glad if you would double check. So we shoudl remove it in the c++ part as well as it is dead code now.  will Do this asap.

2020-04-24 17:50 UTC, Niektory commented
Yes I checked, it's removed from all lua files.

2020-04-25 06:18 UTC, Niektory requested changes
Missed one change on line 109, the rest looks good.

( Some of the code using `ProgramResult::kNone` might be obsolete now, but I'm not sure which parts, so maybe better leave them alone to not break anything :) )

2020-04-25 06:18 UTC, Niektory commented on src/logic/map_objects/tribes/production_program.h
> -	///    None               ::= "no_stats"
Remove from line 109 as well?

2020-04-25 10:46 UTC, hessenfarmer commented on src/logic/map_objects/tribes/production_program.h
> -	///    None               ::= "no_stats"
I left this in line 109 due to this state may still happen if a program doesn't get start.

2020-04-25 13:52 UTC, Niektory commented on src/logic/map_objects/tribes/production_program.h
> -	///    None               ::= "no_stats"
It's in the "Parameter syntax" section of `ActReturn` though. It lists parameters that can be used when returning. So the "not started" state doesn't apply here I think.

2020-04-25 18:13 UTC, hessenfarmer commented on src/logic/map_objects/tribes/production_program.h
> -	///    None               ::= "no_stats"
ok I'll remove it thanks for reviewing.

2020-04-25 18:17 UTC, Niektory approved these changes

2020-04-26 13:11 UTC, hessenfarmer commented
Niektory has approved this but git doesn't recognize. 
I would be interested why this is the case and how to fix this as he showed great ability codewise.
So he should be allowed approving 

As the branch is approved it should be merged

2020-04-26 13:19 UTC, merged

2020-04-26 13:22 UTC, Noordfrees commented
@hessenfarmer you are an admin, right? So you can merge PRs yourself even if automatic merging is blocked.
@Niektory please request to join the team widelands/elders then you'll have push access to origin and your reviews count for automatic merging

2020-04-26 20:59 UTC, hessenfarmer commented
@Noordfrees 
Yes I am but it felt wrong to merge my own stuff without a properly recognized review so I hesitated. I would use it for travis or appveyor things and so on

2020-04-27 04:12 UTC, Niektory commented
Oops, a small problem slipped through. The changes to training sites' `sleep` programs cause them to increase productivity when there are no soldiers inside. I guess we need `return=failed` or `return=skipped` in place of `return=no_stats` there.

2020-04-27 08:32 UTC, hessenfarmer commented
will look into it tonight.

2020-04-27 08:40 UTC, hessenfarmer commented
@tppq 
As I assume you understood the code of the trainingsite could you please explain under which circumstances the sleep program is called. Thanks in advance

2020-04-27 12:09 UTC, Niektory commented
Hmm... I found 2 places.

This one is called when all upgrade priorities are 0 and all upgrade credits are less than 10; I have no idea when that happens:
https://github.com/widelands/widelands/blob/3dcdf52b09aacc2cf1f687e190b566503715b8a3/src/logic/map_objects/tribes/trainingsite.cc#L799-L801

This is called when there are no soldiers present at the training site with upgradable level for the attempted upgrade type:
https://github.com/widelands/widelands/blob/3dcdf52b09aacc2cf1f687e190b566503715b8a3/src/logic/map_objects/tribes/trainingsite.cc#L830-L831