Campaign Empire 02: improved scenario continuity
widelands/widelands pull request #4038
Opened 2020-07-31 13:08 UTC by pospec4444

This fixes both #3930 issues at once.

* Added intermediate "expand south" objective to "marble mine" part
For "No objective after food infrastructure objective" issue.

* Synchronized "marble mine" and "mining/food infrastructure"
For "Possible deadlock: out of marble columns" issue.
If player ignores expansion **and** runs out of columns, he is reminded by new objective "expand south". After expansion, new mining objective starts and Stonemason's house is enabled.

Tested by passive, objective-driven play.

2020-08-02 06:45 UTC, gunchleoc requested changes
Player now has to expand south before they can build a stonemason - that needs to be unblocked.

2020-08-02 06:45 UTC, gunchleoc commented on data/campaigns/emp02.wmf/scripting/texts.lua
> +      _([[When you get there, continue with expansion to the south. That area seems also promising.]]))
```suggestion
      _([[When you get there, continue with expansion to the south. That area also seems promising.]]))
```

2020-08-02 06:45 UTC, gunchleoc commented on data/campaigns/emp02.wmf/scripting/texts.lua
> +      li(_[[Expand to the south of marble mountain.]])
```suggestion
      li(_[[Expand farther to the south of the marble mountain.]])
```

2020-08-02 06:45 UTC, gunchleoc commented on data/campaigns/emp02.wmf/scripting/texts.lua
> +   body = objective_text(_"Continue expansion",
```suggestion
   body = objective_text(_"Continue Expansion",
```

2020-08-02 10:19 UTC, pospec4444 commented
> Player now has to expand south before they can build a stonemason - that needs to be unblocked.

That's what I tried to address/explain by:

> If player ignores expansion **and** runs out of columns, he is _reminded_ by new objective "expand south". After expansion, new mining objective starts and Stonemason's house is enabled.

Is this OK? https://github.com/widelands/widelands/pull/4038/commits/9dbaa015a54d647f27998940541891bd124e3c76

2020-08-02 13:03 UTC, gunchleoc commented
There is an objective that explicitly asks the player to build a stonemason - I still think this should come immediately after the marble mine is finished, because it is teaching the player how to use the marble. Also, if the player should happen to build a stonemason on their own before the food infrastructure is finished, the "Build a stonemason" objective no longer makes sense.

We should put this in a separate function to run in its own thread.

2020-08-02 14:02 UTC, pospec4444 commented
> There is an objective that explicitly asks the player to build a stonemason

It's not that explicit:
https://github.com/widelands/widelands/blob/d185afc7e6795ba4f3cd9b22fa0fb7c837282b5b/data/campaigns/emp02.wmf/scripting/texts.lua#L59-L66

It is just one part of the objective:
https://github.com/widelands/widelands/blob/d185afc7e6795ba4f3cd9b22fa0fb7c837282b5b/data/campaigns/emp02.wmf/scripting/mission_thread.lua#L136-L161


> I still think this should come immediately after the marble mine is finished, because it is teaching the player how to use the marble.

Like start "mining infrastructure" objective right after marble mine is built?

2020-08-02 14:28 UTC, gunchleoc commented
It does say to build a stonemason's house, which is the part I'm interested in.

What I mean is we should have `obj_build_marblemine` done => start `obj_build_mining_infrastructure` and do not wait for expansion south.

2020-08-06 06:34 UTC, gunchleoc approved these changes

2020-08-06 06:35 UTC, merged