Clear some clang-analyzer checks
widelands/widelands pull request #4051
Opened 2020-08-02 18:11 UTC by gunchleoc

* `clang-analyzer-core.CallAndMessage`
* `clang-analyzer-core.DivideZero`

2020-08-02 19:00 UTC, Noordfrees requested changes
Some of those safety checks look just stupid to me. What's the point of using `std::max(1, infspace_count)` directly after `assert(infspace_count > 0);`? Or using `closest ? closest->serial() : 0` after `assert(closest);`? That is ugly.

2020-08-02 19:00 UTC, Noordfrees commented on src/economy/ferry_fleet.cc
> +		Ferry* ferry = idle_ferries.front();
Bug! See 17 lines below

2020-08-05 07:00 UTC, gunchleoc commented on src/economy/ferry_fleet.cc
> +		Ferry* ferry = idle_ferries.front();
Should be fixed now

2020-08-05 07:03 UTC, gunchleoc commented
> Some of those safety checks look just stupid to me. What's the point of using `std::max(1, infspace_count)` directly after `assert(infspace_count > 0);`? Or using `closest ? closest->serial() : 0` after `assert(closest);`? That is ugly.

This is safer for release builds, where the assert isn't being checked. I have already found at least one instance in the code where asserts are dependent on input from Lua files, which is a bug, because we can't assert that.

If you still think these are too ugly, I can revert them though and tag them as `// NOLINT`

2020-08-06 15:03 UTC, Noordfrees reviewed
Okay then. One comment inline where I would really prefer a NOLINT.

2020-08-06 15:03 UTC, Noordfrees commented on src/economy/flag.cc
> +			    worker.serial(), serial(), state ? state->objvar1.serial() : 0);
Will never be null because we have a `if (state == nullptr) { return true; }` a few line above

2020-08-07 06:43 UTC, Noordfrees approved these changes

2020-08-08 05:50 UTC, merged