Speedup player vision packet
widelands/widelands pull request #4113
Opened 2020-08-13 09:51 UTC by gunchleoc

Closes https://github.com/widelands/widelands/issues/4109

Not as fast as it used to be, but workable. I used the same trick as for the player statistics.

Also, nodes that were never seen are skipped.

2020-08-16 06:42 UTC, gunchleoc commented
This is ready now.

2020-08-20 11:36 UTC, klaus-halfmann requested changes
Please document the strings emitted - will be needed in case wea must examine such a file.

Please either refactor this into smaller fucntions,
or - better - invent some iterator/labda fucntion aproach to avoid the duplicated code.

I wonder why our streams are not buffered so that we gain such a big speed?

Will testplay europe now anyway ....

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				parseme = fr.c_string();
Please add example of expected string like n|m wheren n and m are ...

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +					continue;
Comment: How can this happen? does not each player see _some_ fie lds?

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +
assert (counter == no_of_seen_fields) ??

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				// Owner
Better: parse list of Owner (IDs ?) seperatred by |

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				// Map objects
Do .... with Map objects

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +unsigned to_unsigned(bool value) {
inline

2020-08-20 11:36 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +			std::ostringstream oss("");
Can we presize oss based on some reasomnable estimation?

2020-08-21 09:33 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +			std::ostringstream oss("");
It's constructor doesn't have a pre-sizing argument, so no, I don't think so.

2020-08-21 09:35 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +				// Map objects
I don't understand what you mean.

2020-08-21 09:36 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +				// Owner
Isn't that what I am doing with `boost::split(field_vector, parseme, boost::is_any_of("|"));`?

2020-08-21 09:38 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +
Will do :)

2020-08-21 09:38 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				// Owner
Its only about the comment
// Owner -> parse list of Owner (IDs ?) seperated by |

2020-08-21 09:39 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				// Map objects
// Map objects -> // Parse the Map Objects from a string like 'X|y|z ..."

2020-08-21 09:40 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +					continue;
The game is saveloaded before it starts in order to create a backup copy, so it happens there.

2020-08-21 09:42 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +					continue;
continue; // happens in Map Editor or on first file of a replay

2020-08-21 09:47 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +				parseme = fr.c_string();
Does something like this do?
```
// Some data for all player fields
// While saving, we iterated all fields for a property and separated the fields by '|'.
std::vector<std::string> field_vector;

// Single complex record for a field
// If a property is multidimensional (e.g. each field has 3 roads), the values are separated by '*'.
std::vector<std::string> data_vector;
```

2020-08-21 09:49 UTC, klaus-halfmann commented on src/map_io/map_players_view_packet.cc
> +				parseme = fr.c_string();
Fine!

2020-08-21 09:52 UTC, gunchleoc commented
> Please either refactor this into smaller fucntions,
> or - better - invent some iterator/lambda function aproach to avoid the duplicated code.

We would end up with a separate function for each loop, because the code is not uniform enough. So, lambda functions like I used for the player statistics code won't add any readability.
 
> I wonder why our streams are not buffered so that we gain such a big speedup?

Me too. I had a quick look and decided not to go there.

2020-08-21 10:10 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +				// Owner
I have added some comments now.

2020-08-21 10:12 UTC, gunchleoc commented on src/map_io/map_players_view_packet.cc
> +				// Map objects
I'm not using the string trick for the map objects.

2020-08-21 16:11 UTC, klaus-halfmann commented
I used the new (great) continue game fature and got:
```
Reading Objective Data ... took 23ms
Reading Scripting Data ... PANIC: unprotected error in call to Lua API (bad permanent value (no value))
Abort trap: 6
```

normal multiplayer worked as expected ....

2020-08-22 08:29 UTC, klaus-halfmann approved these changes
Played  Europe with all Slots filled with AIs fore some hours. 
Autosave felt not as bad as before.

2020-08-22 11:31 UTC, gunchleoc commented
> I used the new (great) continue game fature and got:
> 
> ```
> Reading Objective Data ... took 23ms
> Reading Scripting Data ... PANIC: unprotected error in call to Lua API (bad permanent value (no value))
> Abort trap: 6
> ```
> 
> normal multiplayer worked as expected ....

That's a different package and doesn't reproduce for every game. So, unrelated to this branch.

2020-08-22 11:38 UTC, merged

2020-08-22 12:57 UTC, Noordfrees commented on src/map_io/map_players_view_packet.cc
> +					seen_fields.insert(&f);
This is a bit late now, but…
why are you also saving fields in `kVisible` state? These will be rediscovered automatically anyway when the MapObject seeing them is being loaded. I have the feeling that this packet just became a lot slower…

2020-08-22 13:03 UTC, Noordfrees commented on src/map_io/map_players_view_packet.cc
> +					seen_fields.insert(&f);
by changing this I can reduce the write time for Europa with Fogless from now 125s to 7s. Will make a PR