Separate tribes
widelands/widelands pull request #4134
Opened 2020-08-18 18:23 UTC by gunchleoc

Separate the definitions of each tribe into separate files

* Get rid of global init and preload files
* Define each tribe separately in a `tribes/<tribe_name>` directory
* Shift starting condition and image files into each tribe's directory
* Shift wares' and workers' `default_target_quantity` and `preciousness` to tribe definitions
* Reduce number of disk reading operations in game loading screens

There will be another branch for the tribe-dependent help files.

2020-08-19 11:48 UTC, hessenfarmer approved these changes
Code LGTM.
Not tested.
only the tribes/tribes Pathname looks confusing, what about tribes/basics/ or tribes/basic_info or tribes/initialisation

2020-08-19 11:49 UTC, hessenfarmer commented
BTW: I hope you are aware that all the refactoring does cost me some time to adopt amazons as well ;-)

2020-08-19 12:28 UTC, gunchleoc commented
> BTW: I hope you are aware that all the refactoring does cost me some time to adopt amazons as well ;-)

Yes, I am. We need this for moddability though. This series of branches is the only one you need to implement right now, the program refactorings all have compatibility code and can be done later.

Do let me know if you want my help, I'd be happy to do the conversion for the amazons.

> what about tribes/basics/ or tribes/basic_info or tribes/initialisation

When I refactor the world too, we might end up with something different, e.g. `units/tribes` and `units/world` or something like that. I am planning to refactor the world too in order to keep our API orthogonal.

2020-08-19 13:48 UTC, hessenfarmer commented
> 
> 
> > BTW: I hope you are aware that all the refactoring does cost me some time to adopt amazons as well ;-)
> 
> Yes, I am. We need this for moddability though. This series of branches is the only one you need to implement right now, the program refactorings all have compatibility code and can be done later.
> 
> Do let me know if you want my help, I'd be happy to do the conversion for the amazons.    
    
Well I have already done most of it and just need to incorporate the tribes_filtering branch and this one. At least i do learn and understand a lot of things while doing so. So no worries. Better moddability is worth the pain in any case.  

> 
> > what about tribes/basics/ or tribes/basic_info or tribes/initialisation
> 
> When I refactor the world too, we might end up with something different, e.g. `units/tribes` and `units/world` or something like that. I am planning to refactor the world too in order to keep our API orthogonal.

This I don't understand. I think the API's should be as consistnet as they can be. However we should not mix the world and the tribes in their file structure. So Ifound it just confusing and tried to propose a more "telling" folder name.

2020-08-19 14:24 UTC, gunchleoc commented
I'll definitely keep the world and tribes separate for now. Merging paths at the end can always be done more easily than pulling them apart again. It will be easier to make this decision once everything else has been done.

Let's go with `tribes/initialisation` for now.

2020-08-20 06:18 UTC, hessenfarmer requested changes
found some typo to be corrected

2020-08-20 06:18 UTC, hessenfarmer commented on doc/sphinx/extract_rst.py
> +    ('data/tribes/initialisation/atlanteans', '', 'lua_tribes_defining'),
now we have a typo here I believe

2020-08-20 06:18 UTC, hessenfarmer commented on utils/buildcat.py
> +        '../../data/tribes/initialisation/*/starting_conditions/*.lua',
typo

2020-08-20 06:18 UTC, hessenfarmer commented on data/tribes/initialization/atlanteans/units.lua
> +-- The ``tribes/initialisation/<tribename>/units.lua`` file configures the units that a tribe can use.
typo initialisation --> initialization

2020-08-20 06:18 UTC, hessenfarmer commented on data/tribes/initialization/atlanteans/units.lua
> +-- The file **has to be located in** ``tribes/initialisation/<tribename>/init.lua`` so that the engine can find it.
typo

2020-08-20 06:18 UTC, hessenfarmer commented on utils/buildcat.py
>      ('tribes/tribes', [
does this need to be changed as well?

2020-08-20 10:19 UTC, gunchleoc commented
Should be all fixed now. I went with `tribes/initialization` in the end, since we're using American and not British English.

2020-08-20 10:29 UTC, hessenfarmer commented
> 
> 
> Should be all fixed now. I went with `tribes/initialization` in the end, since we're using American and not British English.

that's why I just commented the BE String.  What about the last unresolved comment though?

2020-08-20 18:12 UTC, gunchleoc commented
> > Should be all fixed now. I went with `tribes/initialization` in the end, since we're using American and not British English.
> 
> that's why I just commented the BE String. What about the last unresolved comment though?

I don't know what I'm supposed to do there, I have already fixed the path for the starting conditions.

2020-08-20 21:58 UTC, hessenfarmer approved these changes
forget my last comment I was confused by only wathing the diff tribes/tribes is not a pathname there.
Code LGTM. 
not tested

2020-08-24 02:09 UTC, merged

2020-08-24 18:06 UTC, hessenfarmer commented
while adopting amazons it arose to me the question what might be the reason of only atlanteans having the toolbar images?

2020-08-26 12:42 UTC, gunchleoc commented
> while adopting amazons it arose to me the question what might be the reason of only atlanteans having the toolbar images?

They are placeholder image to show that the code works. We need an art contribution to give the toolbar a nice frame. https://github.com/widelands/widelands/issues/1092

I also kept them optional so you don't have to provide any, lacking an artist.