Program documentation
widelands/widelands pull request #4140
Opened 2020-08-21 09:02 UTC by gunchleoc

* Update Production Program documentation
* Modernize tribe code for empire scenario 4

All that's left to do now is to update the animations' sound priority to percent notation, and then the program API overhaul is done :)

2020-08-21 12:09 UTC, hessenfarmer approved these changes

2020-08-21 12:09 UTC, hessenfarmer commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
this doesn't work on my Windows machine unless I add "map:" .. in front of the path.dirname

2020-08-21 12:10 UTC, hessenfarmer requested changes
see my comment 
see also https://www.widelands.org/forum/topic/4926/
which might be related to that

2020-08-21 13:02 UTC, gunchleoc commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
The helptexts will get a different handling soon, but we do need to fix the problem with the animations.

2020-08-21 18:30 UTC, hessenfarmer commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
well as the fix for the helptext in this particular case is easy we might simply add it in.

2020-08-22 10:55 UTC, gunchleoc commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
I have deleted the line to avoid merge conflicts with https://github.com/gunchleoc/widelands/commit/66509b76460f5267f110b15218995d4e6c6c9007

2020-08-22 14:34 UTC, gunchleoc commented
I have undone the animation changes to the scenario now - better safe than sorry.

2020-08-22 19:30 UTC, hessenfarmer commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
Is the undelete of the line intentional. if yes why shouldn't we add just the "map:/" .. string to make it work for the moment being . Otherwise we should reopen #4020

2020-08-22 19:33 UTC, hessenfarmer approved these changes
Changes themselves are ok.
not tested though

2020-08-22 20:37 UTC, gunchleoc commented on data/campaigns/emp04.wmf/scripting/tribes/temple_of_vesta/init.lua
>     helptext_script = path.dirname(__file__) .. "helptexts.lua",
I expect to open a PR with a fix for the helptexts tomorrow.

2020-08-23 15:27 UTC, merged