Fast fix for the drop up menu bug #4341
widelands/widelands pull request #4363
Opened 2020-10-14 17:25 UTC by flegmaatikko

Here is my first solution for the bug #4341 
I created a new method that shows where the target button is and did minor changed to the texts. There is also an unused method that opens the menu only. It can be removed if needed.

The mouse pointer moves over the menu but not over to the button. Instead of moving the mouse pointer I tried to show the position of target menu item by highlighting the buttons step by step from bottom to up.

This is just a fist draft and I look forward to get some feedback.

2020-10-15 07:41 UTC, gunchleoc commented
I like it, you can continue like that for the other dropdowns in this turorial :)

2020-10-16 18:13 UTC, flegmaatikko commented
Hopefully all the cases are fixed now.

2020-10-18 05:12 UTC, gunchleoc requested changes

2020-10-18 05:12 UTC, gunchleoc commented on data/campaigns/tutorial01_basic_control.wmf/scripting/helper_functions_demonstration.lua
> +   local ind = wl.ui.MapView().dropdowns[name]:get_no_of_items()
```suggestion
   local ind = wl.ui.MapView().dropdowns[name].no_of_items()
```

2020-10-18 05:12 UTC, gunchleoc commented on src/scripting/lua_ui.cc
> +   METHOD(LuaDropdown, get_no_of_items),
Remove this. It's available as a property and we don't need to add a method too.

2020-10-20 06:50 UTC, gunchleoc approved these changes

2020-10-20 06:51 UTC, merged