Increase player info packet version
widelands/widelands pull request #4581
Opened 2021-01-03 12:00 UTC by Noordfrees

Fixes #4579 
This necessity was overlooked in #4549 so it has to be done now.

**Please review this urgently** because savegames created with a9cdcfb0a2fa9fd9a3d77837509e74900b663910 or later may be incompatible after this fix.

2021-01-03 12:20 UTC, klaus-halfmann approved these changes
Change is obvious, wont do any testing, yet.
Do we need to check some old and new Savegames?

2021-01-03 12:28 UTC, Noordfrees commented
For testing best check that savegames newly created with this branch load correctly and that pre- a9cdcfb savegames (e.g. the one from the linked issue) also load

2021-01-03 15:10 UTC, klaus-halfmann requested changes
I fail to play / load any game, I assume there is ome extra code mssing somewhere?

Here som examples:

Starting a simple crater network game
[00:07:45.243 real] ERROR:   FATAL EXCEPTION: Unknown immovable 'berry_bush_blueberry_small'
[00:07:45.243 real] ERROR:   You are using build 1.0~git25107[8ee1023@4579-packet-version-error] (Debug).

Starting a random single player game:
[00:05:50.101 real] ERROR:   FATAL EXCEPTION: Unknown immovable 'berry_bush_blueberry_small'

Loading some savegame from R20:
[00:05:00.185 real] ERROR:   FATAL EXCEPTION: [../src/logic/map_objects/tribes/productionsite.cc:443] barbarians_coalmine_deep (48723) has no InputQueue for unknown ware 86

Not sure how I produced these two:
[00:01:25.658 real] ERROR:   FATAL EXCEPTION: player info: Error while loading tribe 'i?': DescriptionManager::load_description: Object 'i?' was not registered

Map from original Bug:
[00:00:58.370 real] ERROR:   FATAL EXCEPTION: player info: Error while loading tribe 'europeans': DescriptionManager::load_description: Object 'europeans' was not registered

Anyway it is impossible to play any map at all...

2021-01-03 15:43 UTC, Noordfrees commented
I cannot reproduce any of this (except "Object 'europeans' was not registered" – this is not a bug because the user used a custom tribe in that savegame)…
Can you check that the widelands checkout and the build directory are clean?

2021-01-03 16:46 UTC, klaus-halfmann commented
Mhh, I compiled it from sratch:
$ git log -2
commit 8ee1023b20dfdbb4cbd4d7ebb8655349790d0474 (HEAD -> 4579-packet-version-error, origin/4579-packet-version-error)
Author: Benedikt Straub <benedikt-straub@web.de>
Date:   Sun Jan 3 12:56:35 2021 +0100
    Increase player info packet version
commit 548228535a0b638f61cd279bb122b275c1ea3459 (origin/master, origin/HEAD)
Author: Benedikt Straub <48293446+Noordfrees@users.noreply.github.com>
Date:   Sun Jan 3 12:36:13 2021 +0100
    Main Menu Redesign, Part 5 (#4572)

$ git status
On branch 4579-packet-version-error
Your branch is up to date with 'origin/4579-packet-version-error'.
nothing to commit, working tree clean

Will tyr with a "clean" crate save from master again

2021-01-03 16:55 UTC, klaus-halfmann commented
Tryed a clean save form crater,
FATAL EXCEPTION: player info: Error while loading tribe 'i?': DescriptionManager::load_description: Object 'i?' was not registered
mater has no such Issue

This my indicate:
* loading an object with os-dependant size (plain int or such)
* Some extra changes on your side

It must be related to that code as the tribename is garbeld (which i read directly after thta code).
Maybe you can add some debug code on write and read wit the rgb.values?

I will throw a debugger at it - tomorrow.

2021-01-03 19:43 UTC, Noordfrees commented
You're sure the savegame was created with this branch as well?
If I try to create a new savegame with master it will fail to load with this branch ("`Error while loading tribe 'i�': DescriptionManager::load_description: Object 'i�' was not registered`") – this is expected, we unfortunately have to break compatibility for savegames created with the master versions 548228535a0b638f61cd279bb122b275c1ea3459, bccc375b87d2a0c7445dc2582f6b39161014e5ba, f997864954af1ce79d5aed7409734b7d98b7762d, and a9cdcfb0a2fa9fd9a3d77837509e74900b663910.

2021-01-04 06:34 UTC, klaus-halfmann commented
Did some fresh tests now: single and multiplayer games and saveloading are ok with this fix.
Sgould we be able to load R20 savegames?

2021-01-04 06:50 UTC, klaus-halfmann approved these changes
Loading R20 Savegames was OK. Loading some older R21 Savegame was ok (gave me a crash later, should be unrelated).
Got a nasty recursive/repeated SIGABRT crash. with some 1001 Wells testgame from November.
So this is ok for me for now and should go into master.

How are our plans for the next release? Looks we should start some bughunting now?
We have so many nw features, I actually can not name all of them.

I have only time this week and would like to do more, other reviews.

2021-01-04 11:06 UTC, merged

2021-01-04 11:27 UTC, Noordfrees commented
> How are our plans for the next release? Looks we should start some bughunting now?
> We have so many nw features, I actually can not name all of them.

True, I agree. I opened a discussion: https://github.com/widelands/widelands/discussions/4585
 
> I have only time this week and would like to do more, other reviews.

Great :) there are lots of PRs open that have not been looked at yet at all