Blinking caret
widelands/widelands pull request #4860
Opened 2021-05-15 17:49 UTC by jmoerschbach

Blinking caret for EditBox and MultilineEditBox as one is used to from text input widgets

2021-05-20 10:39 UTC, Noordfrees commented on src/graphic/wordwrap.cc
> +static const int CARET_BLINKING_DELAY = 500;
Please use `constexpr` instead of `static const`. Would it be possible to place this variable somewhere where both `WordWrap` and `EditBox` can access it, so we need it only once?

2021-05-20 10:44 UTC, Noordfrees requested changes
This crashes when closing the editor map options with verbose output enabled:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::io::too_many_args>'
  what():  boost::too_many_args: format-string referred to fewer arguments than were passed
Abgebrochen (Speicherabzug geschrieben)
```
Best add code to the ScopedTimer destructor to skip printing a message if the message string is empty

2021-05-22 22:04 UTC, jmoerschbach commented on src/graphic/wordwrap.cc
> +static const int CARET_BLINKING_DELAY = 500;
changed, I dont see a common place for that constant...

2021-05-22 22:04 UTC, jmoerschbach commented
> 
> 
> This crashes when closing the editor map options with verbose output enabled:
> 
> ```
> terminate called after throwing an instance of 'boost::wrapexcept<boost::io::too_many_args>'
>   what():  boost::too_many_args: format-string referred to fewer arguments than were passed
> Abgebrochen (Speicherabzug geschrieben)
> ```
> 
> Best add code to the ScopedTimer destructor to skip printing a message if the message string is empty

done

2021-05-23 10:01 UTC, Noordfrees commented
This needs a master merge now to clean up the clutter in the diff left by the temporarily broken format bot

2021-05-24 11:51 UTC, Noordfrees commented
The format bot seems to refuse work on your repo :( 
https://github.com/jmoerschbach/widelands/runs/2651327672
Perhaps the access token secret is outdated?

2021-05-25 20:24 UTC, jmoerschbach commented
> 
> 
> The format bot seems to refuse work on your repo :(
> https://github.com/jmoerschbach/widelands/runs/2651327672
> Perhaps the access token secret is outdated?

yeah, thx for the hint. looks good now :)

2021-05-26 09:32 UTC, Noordfrees commented
Just a compiler warning left now
```
../src/ui_basic/editbox.h:86:7: warning: 'focus' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void focus(bool topcaller = true);
             ^
../src/ui_basic/panel.h:277:15: note: overridden virtual function is here
        virtual void focus(bool topcaller = true);
                     ^
```
Also the blinking looks just a bit too hectic to me. Could you increase the delay to ~1000?

otherwise LGTM

2021-05-26 19:15 UTC, jmoerschbach commented
all done :)

2021-05-26 19:17 UTC, Noordfrees approved these changes

2021-06-08 12:40 UTC, merged