Chasing the `SupplyList::remove_supply` crash
widelands/widelands pull request #4913
Opened 2021-06-03 07:47 UTC by Noordfrees

Supersedes #4858 

When this is ready, it will hopefully
fix #4533
fix #4645
fix #4792
fix #4857

2021-06-03 10:51 UTC, klaus-halfmann commented
moved the iline functions from SupplyList to nromal fucntions for better debugging.
First glance from XCode: this is aclled when merging/spliiting econonies (which I always try  to avoid 😄)
and when fleets/ships/ports ae involved.

2021-06-03 11:18 UTC, klaus-halfmann commented
Uhhm this change resulst in a desync :-(

```
void SupplyList::remove_supply(Supply& supp) {
	for (Supplies::iterator item_iter = supplies_.begin(); item_iter != supplies_.end();
	     ++item_iter) {
		if (*item_iter == &supp) {
                        // why this way?
			// *item_iter = *(supplies_.end() - 1); // copy last elemnt to current positon
			// supplies_.pop_back();                // remove lasr element duplicated above
            supplies_.erase(item_iter);
			return;
		}
	}
	throw wexception("SupplyList::remove: not in list");
}
```

2021-06-03 14:18 UTC, klaus-halfmann commented
This SupplyList::remove_supply can not work wen the vector has just one element or is empy? 
Why does this not happen normally?

2021-06-03 16:13 UTC, Noordfrees commented
The desync happens because you change the iteration order. What we do now is to overwrite the to-be-deleted entry with the last entry and then delete the last one. Your change simply erases an element without moving the last element. The order in which supplies are iterated is used as a tie-breaker for equally good supplies (or something like that…) so changing it results in a game logic change.

When the vector is empty, the `for` loop is simply skipped because `begin() != end()` is always `false` then. And when it has exactly 1 element, then `*iter = *(end() - 1);` is just a self-assignment, as `iter` and `end() - 1` then both point to the only element. So it is safe in all cases (though not the most elegant implementation).

2021-06-03 17:47 UTC, klaus-halfmann commented
Thanks @Noordfrees for the explaiantion, I adde some code to make the code more debug friendly,
I still crashes but now I get:

==92291==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000603cf8 at pc 0x0001108f91d1 bp 0x7ffee2b171d0 sp 0x7ffee2b171c8
READ of size 8 at 0x611000603cf8 thread T0
    #0 0x1108f91d0 in std::__1::vector<Widelands::Supply*, std::__1::allocator<Widelands::Supply*> >::empty() const vector:664
    #1 0x1108f8c24 in Widelands::SupplyList::remove_supply(Widelands::Supply&) supply_list.cc:51
    #2 0x1106c94a5 in Widelands::Economy::remove_supply(Widelands::Supply&) economy.cc:479
... 
0x611000603cf8 is located 120 bytes inside of 256-byte region [0x611000603c80,0x611000603d80)
freed by thread T0 here:
    #0 0x11a9020bd in wrap__ZdlPv+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x550bd)
    #1 0x10d1cf1b4 in std::__1::_DeallocateCaller::__do_call(void*) new:334
    #2 0x10d1cf198 in std::__1::_DeallocateCaller::__do_deallocate_handle_size(void*, unsigned long) new:292
    #3 0x10d1cf170 in std::__1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long) new:262
    #4 0x10d1cf144 in std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) new:340
    #5 0x10d1ceda5 in std::__1::allocator<char>::deallocate(char*, unsigned long) memory:1673
    #6 0x10d1cd397 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::dealloc() alt_sstream_impl.hpp:302
    #7 0x10d1cd25d in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #8 0x10d1cce54 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #9 0x10d1ccde7 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #10 0x10d1cc994 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #11 0x11130780f in RGBColor::hex_value() const color.cc:35
    #12 0x10d852f23 in StyleManager::color_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGBColor const&) style_manager.cc:387
    #13 0x10ffbe23e in Widelands::Ship::draw(Widelands::EditorGameBase const&, InfoToDraw const&, Vector2<float> const&, Widelands::Coords const&, float, RenderTarget*) const ship.cc:1039
    #14 0x10f792803 in InteractiveSpectator::draw_map_view(MapView*, RenderTarget*) interactive_spectator.cc:113

This is totally unrelated code, but perhaps that formatting has an Issue?

previously allocated by thread T0 here:
     #16 0x10eeca63c in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator%(int const&) format_class.hpp:87
    #17 0x111307614 in RGBColor::hex_value() const color.cc:35
    #18 0x10d852f23 in StyleManager::color_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGBColor const&) style_manager.cc:387
    #19 0x10ffbe23e in Widelands::Ship::draw(Widelands::EditorGameBase const&, InfoToDraw const&, Vector2<float> const&, Widelands::Coords const&, float, RenderTarget*) const ship.cc:1039

[Complete Crash logs](https://github.com/widelands/widelands/files/6593406/Crash.txt)

No idea how / if this helps

2021-06-03 17:55 UTC, klaus-halfmann commented
I found no direct way to trgigger an asan check directly. For now I am lost, may try again next weekend.

2021-06-03 18:06 UTC, Noordfrees commented
To me this looks like the `IdleWareSupply`'s `economy_` is a wild pointer as the ware's economy (and therefore the `Economy`'s member variable `supplies_` as well) was deleted earlier than the ware itself. When I tried to get the ware's location with GDB it told me that the `Player` that owns the `WareInstance` has apparently also been deleted by this time already.
The thing is, a ware can only belong to a worker, flag, or ship. Workers and ships are deleted before wares and delete their wares along with themselves. The wares remaining then delete themselves earlier than the flags so their economies should still exist then. There must be something wrong with the destruction order on deletion but I still have no idea where

2021-06-03 19:32 UTC, Noordfrees commented
The commit I just pushed changes the end-of-game destruction order. Instead of a crash I now get 
```
terminate called after throwing an instance of 'WException'
  what():  [../src/economy/supply_list.cc:52] SupplyList::remove: list is empty
```
which looks a bit better already ;) perhaps this will also be more useful for further debugging

2021-06-04 10:52 UTC, Noordfrees commented
I think I fixed it now :) 
Let's wait what the testsuite says though…

2021-06-04 15:25 UTC, klaus-halfmann requested changes
Will give it a try now

2021-06-04 15:25 UTC, klaus-halfmann commented on src/logic/map_objects/tribes/ship.cc
> +					ware->remove(game);
If this is the fix, please explain this line and that ship_update_idle deserves some refactoring ...

2021-06-04 16:47 UTC, klaus-halfmann requested changes
Whatever you actually did (still no clue).
**this fixed the Issue**. Shall I revert my Changes?
Or shall we set up a "clean" branch with only the acual fix.?

2021-06-04 17:16 UTC, Noordfrees commented
The diff looks fine to me as it is so the branch is good for merging in its current state in my opinion.

The actual fix is a simple oversight: When an expedition ship unloads wares to the new port constructionsite, the wares are "semantically" destroyed but they remained in existence in a non-well-defined state. With this fix they are fully removed when they ought to be.

2021-06-04 17:24 UTC, klaus-halfmann reviewed
Let me (mostly) revert supply_list.h/.cc

2021-06-04 18:42 UTC, klaus-halfmann approved these changes
OK for me now

2021-06-05 05:04 UTC, klaus-halfmann commented
Will merge this (hey my first real merge to master!) tonight unless someone else steps foreward.

2021-06-05 12:44 UTC, Noordfrees commented
No this is not critical so merging should wait until after the release

2021-06-08 12:41 UTC, merged