Added more ship names for Amazon tribes
widelands/widelands pull request #5034
Opened 2021-08-19 02:09 UTC by alasiax

Based on rivers in the Amazon Basin for naming consistency.

2021-08-19 06:39 UTC, frankystone requested changes
Thanks for contributing!

There are some double entries, please fix.

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      pgettext("shipname", "Andirá"),
Two of same name

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      -- TRANSLATORS: This Amazonian ship is named after a river
To of same name, last differs only with the hyphen on last 'a'. I think during a game no one can distinguish between apostroph and hyphen?

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      pgettext("shipname", "Cuieiras"),
Two of same name.

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      pgettext("shipname", "Ipixuna"),
Three of same name.

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      pgettext("shipname", "Pauini"),
Two of same name.

2021-08-19 06:39 UTC, frankystone commented on data/tribes/ships/amazons/init.lua
> +      pgettext("shipname", "Preto"),
Two of same name.

2021-08-20 01:41 UTC, alasiax commented
Thanks Frankystone :o) Updates made as requested.

2021-08-20 06:04 UTC, frankystone approved these changes
LGTM :-)

Let's wait for the checks to finish.

2021-08-20 08:29 UTC, hessenfarmer commented
Nice work thanks a lot

2021-08-20 09:23 UTC, merged