added lore for Dressmakery
widelands/widelands pull request #5037
Opened 2021-08-23 11:24 UTC by alasiax

First commit of this kind, so want to check I've done it right before adding more.
fixes #4981

2021-08-23 11:46 UTC, Noordfrees commented
:+1: 
just please use `’` instead of `'`:
```diff
- Adapted by the Dressmakers' guild from the oral history volume ‘Father Jungle's wisdom: Song on Mindfulness.’
+ Adapted by the Dressmakers’ guild from the oral history volume ‘Father Jungle’s Wisdom: Song on Mindfulness.’
                            ^                                                  ^
```

2021-08-25 04:56 UTC, alasiax commented
I wasn't sure whether to start a new pull request for the tips file. No problem to do so if preferred,

2021-08-25 06:27 UTC, frankystone commented
No need for an additional pull request, as long the changes are related.

Please mark this PR as a 'draft' (see the top right on this page) as long this PR is not ready yet.

2021-08-26 01:55 UTC, alasiax commented
I'm happy for these things to be merged if that's ok? But I'll wait to submit further changes to units.lua until I've got lots of them done at once, and submit one pull request then.

2021-08-26 02:52 UTC, alasiax commented
One last change for this PR/commit to address #4981. I'll wait to make a pull for further changes to the units.lua until a bulk update is ready, but this info is really needed for the Amazons rare tree plantations.

2021-08-26 08:45 UTC, hessenfarmer requested changes

2021-08-26 08:45 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "From ‘Interviews with Mistress WeaverSong’, recorded in the journals of explorer Daezy Baytes."),
I am not sure whether journals and interviews fit to the tribe. Is the explorer Amazonian as well? The lore of a tribe should be based in the tribe. 
So maybe this is just a line from the Liana (cutter) song).

2021-08-26 08:45 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            performance = pgettext("amazons_building", "The liana cutter rests %s before going to work again."):bformat(ngettext("%d second", "%d seconds", 34):bformat(34))
How did you calcualte the 34 seconds as the sleep time is 30 seconds in the init.lua of the liana_cutters_hut

2021-08-26 08:45 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            lore = pgettext("amazons_building", "‘If properly harvested, cured and stored, ironwood becomes almost indestructible, and (unlike its metal namesake) will not rust in damp conditions.’")
I would leave the parts in brackets out.

2021-08-26 08:45 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            purpose = pgettext("amazons_building", "Plants rare trees which are needed by the Amazons, like balsa, rubber and ironwood. Rare trees are planted according to the economy requirements.")
from my perspective the Part about the economy should go to the note as well, to have the reason and the countermeasure in one place

2021-08-26 08:45 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Adapted by the Dressmakers’ guild from the oral history volume ‘Father Jungle’s wisdom: Song on Mindfulness.’"),
I am not sure whether a concept of guilds fit to the Amazons. Furthermore I am unsure whether a pure female tribe would call the jungle father although this might be possible if they feel to be daughters of the jungle and her mother. 
Oral history might be misleading as this is a special part in science to document the experienced time by recording interviews of relevant people for future examination. What about "oral traditions collection" .
Last I think mindfulness is regarded to pay attention to the needs of yourself or other people. I believe what is meant here is to pay attention and concentration into your work.  Suggestion migjht be "diligence" or "preciseness"
in full sentence: "Ethos of the Dressmakers - Adapted from the Oral traditions collection ‘Father Jungle’s wisdom: Song on diligence.’

2021-08-26 08:45 UTC, hessenfarmer commented on data/txts/tips/amazons.lua
> +      seconds = 7
maybe we should shorten the display a bit as the loading will not take that long anymore. but this apllies to all tips of all tribes probably

2021-08-26 09:42 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            performance = pgettext("amazons_building", "The liana cutter rests %s before going to work again."):bformat(ngettext("%d second", "%d seconds", 34):bformat(34))
It was most likely in the code from wherever I copied it from, and I forgot to change it.

2021-08-26 10:41 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            lore = pgettext("amazons_building", "‘If properly harvested, cured and stored, ironwood becomes almost indestructible, and (unlike its metal namesake) will not rust in damp conditions.’")
Will change.

2021-08-26 10:42 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            purpose = pgettext("amazons_building", "Plants rare trees which are needed by the Amazons, like balsa, rubber and ironwood. Rare trees are planted according to the economy requirements.")
No problems.

2021-08-26 10:45 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Adapted by the Dressmakers’ guild from the oral history volume ‘Father Jungle’s wisdom: Song on Mindfulness.’"),
Thank you for such a detailed and thoughtful reply on this. I was trying to bring in from the my understanding of the lore as given at https://www.widelands.org/wiki/AmazonsPage/ and what I gathered from the Forum thread. Thank you also for your thoughts there too. 

I had thought that maybe the Amazons are primarily an oral traditions tribe, and as you surmised above, the journals entries are from an outsider. I am very grateful for your thoughts and feedback on this, and for your awareness of oral history as a science. I am happy to write lore as being from within the tribe, no problem. I only used that as a mechanism to explain how the written text might have occurred, but that's perhaps overthinking it. I think this is worth fleshing out more, maybe on the forums?

I'll change the notations as listed above and submit again, because I'd like to see the tips and help for plantations included sooner rather than later.

2021-08-26 14:05 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Adapted by the Dressmakers’ guild from the oral history volume ‘Father Jungle’s wisdom: Song on Mindfulness.’"),
definitly +1 to discuss this in the forums as well, or even to discuss it primarily there. this would make review of changes free of personal opinion if we can get an agreement on some principle characteristics of the tribe

2021-08-26 14:05 UTC, alasiax commented on data/txts/tips/amazons.lua
> +      seconds = 7
I'll add that to my to-do list ;o) 
There is at least one tip in the general ones (about the barracks) which needs review.

2021-08-26 14:14 UTC, hessenfarmer commented
Looks much better now. two last questions: Who are or have been the persons cited? i.e. the jungle master abraxisi and mistress Weaversong.    

I reread the amazons page due to your link above and according to the page (which itself should incorporate the Female part though). Ther it is said that they call the Jungle "mother jungle" and the river " father river " so we might need a little change above

2021-08-26 15:17 UTC, alasiax commented
For now is it ok to leave in Jungle Master Abacaxis (named for the river, but this is a duplicate name of a ship) and Mistress Weaversong (as a name for someone who is a Ropeweaver by trade)? I think that's still nicer than "Text needed" until we've had discussion on the lore. Mother Jungle has now given us "Song of the Conscientious." :o)

As part of the lore discussion, we probably should address whether Jungle Master is the appropriate title, and if so, use that apellation for all lore/authors eg using Master instead of Mistress for respected elders.

2021-08-26 15:19 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Adapted by the Dressmakers’ guild from the oral history volume ‘Father Jungle’s wisdom: Song on Mindfulness.’"),
Awesome, I'll make the thread.

2021-08-26 15:53 UTC, hessenfarmer commented
> 
> 
> For now is it ok to leave in Jungle Master Abacaxis (named for the river, but this is a duplicate name of a ship) and Mistress Weaversong (as a name for someone who is a Ropeweaver by trade)? I think that's still nicer than "Text needed" until we've had discussion on the lore. Mother Jungle has now given us "Song of the Conscientious." :o)

if the change from father to mother is done this can go in. I will approve and merge if the checks are green then.
However my question was targeted in a different direction. Writing th lore is to some extent defining the history and traditions of the tribe (see barbarian lore for that) so I was asking whether you already made up your mind about the legends, heros and stories of this tribe. Abacaxis is ok as name, even if duplicated (the river might have been named after him or he has been named after the river. WeaverSong sounded not that amazonian to me but might be a nickname or something (although I would love a name sounding more like amazonian environment.    
    
> 
> As part of the lore discussion, we probably should address whether Jungle Master is the appropriate title, and if so, use that apellation for all lore/authors eg using Master instead of Mistress for respected elders.   
   
Well, master as word to describe the skill of a worker can be used for both genders according to my dictionaries. Master as part of the name is more a title and a Mistress might be better for female amazonian legends.   
e.g. Amazonia is a very talented jungle master.  But Mistress Amazicaba was the first jungle master to turn bad lands into fertile soil for ironwood trees. But for the title we might use the portugues word "mestra" or any other female Title.

2021-08-26 16:41 UTC, hessenfarmer commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Dressmakers’ ethos, adapted from the traditional verse ‘Father Jungle’s wisdom: Song of the Conscientious.’"),
this is where the change to mother should be done

2021-08-26 17:35 UTC, alasiax commented on data/tribes/initialization/amazons/units.lua
> +            lore_author = pgettext("amazons_building", "Dressmakers’ ethos, adapted from the traditional verse ‘Father Jungle’s wisdom: Song of the Conscientious.’"),
Thank you. Apologies, I forgot to push it up as it's very late here.

I agree with you on the use of master as an expert, but I am conscious that English is not the first language for some players, and this may be a little confusing for a women's tribe. Maybe 'expert' might be a better fit (acknowledge that it will break save compatibility)? Would the tribe seek to master the jungle if they are about living in harmony with the jungle, or rather to work within it and harness and replace the existing resources and grow their knowledges?

2021-08-26 18:59 UTC, hessenfarmer approved these changes
looks good now.
thanks for the work and the patience

2021-08-27 07:38 UTC, alasiax commented
> 
> 
> looks good now.
> thanks for the work and the patience

More like I should thank you! I appreciate the guidance.

2021-08-27 11:39 UTC, merged