Resolve thread sanitizer issues
widelands/widelands pull request #5114
Opened 2021-11-13 15:27 UTC by matthiakl

- Added option to compile with thread sanitizer for future multithreading debugging
- Fixed #5031 (apart from some 3rd party issues in libpulse) 
- Reduced issues reported during creation of a new game from 87 to 33, mostly by using atomic types.

The remaining issues can be boiled down to the `NoteThreadSafeFunction` handling, which I currently don't quite understand ;)
[tsan.txt](https://github.com/widelands/widelands/files/7532304/tsan.txt)

2021-11-13 16:49 UTC, Noordfrees reviewed
Looks very good, will try this out later :)

2021-11-13 16:49 UTC, Noordfrees commented on src/map_io/map_players_view_packet.cc
> +					                  static_cast<DescriptionIndex>(fr.unsigned_32())});
Calling several function of FileRead in the same statement is dangerous, please store them in local variables first. 
Guaranteed execution order? Some compilers are above that ;)

2021-11-13 16:49 UTC, Noordfrees commented on src/logic/map_objects/tribes/soldier.cc
> +			const Field& f = game.map().operator[](soldier->get_position());
Good catch :+1:

2021-11-13 18:11 UTC, klaus-halfmann commented
Checking this, too. Maybe I find my  #5111

2021-11-13 18:13 UTC, klaus-halfmann requested changes
Did not compile:
```
5031-tsan/src/logic/game.h:42:20: error: constexpr variable 'kStatisticsSampleTime' must be initialized by a constant expression
constexpr Duration kStatisticsSampleTime = Duration(30 * 1000);
                   ^                       ~~~~~~~~~~~~~~~~~~~
031-tsan/src/logic/game.h:42:44: note: non-constexpr constructor 'Duration' cannot be used in a constant expression
constexpr Duration kStatisticsSampleTime = Duration(30 * 1000);
                                           ^
5031-tsan/src/base/times.h:38:2: note: declared here
        Duration(const Duration& other) : value_(other.get()) {
        ^
1 error generated.
```

2021-11-14 10:57 UTC, klaus-halfmann commented
@matthiakl I still get the compiler error and clang_tidy is failing shall I try to fix these?

2021-11-14 12:04 UTC, matthiakl commented
> @matthiakl I still get the compiler error and clang_tidy is failing shall I try to fix these?

I am working on it, gcc does too lose checks for constexpr, so I have to check with clang.

2021-11-14 12:44 UTC, matthiakl commented
@klaus-halfmann it should compile now with other compilers.

2021-11-14 17:29 UTC, klaus-halfmann commented
Thanks, compiles now, but I still get #5111 without further clue. Will do codecheck later.

2021-11-14 17:33 UTC, klaus-halfmann commented
Uhm, how Do I activate the TSAN?

2021-11-14 17:44 UTC, klaus-halfmann commented
Those docs should help https://www.cplusplus.com/reference/atomic/atomic/

2021-11-14 17:51 UTC, klaus-halfmann reviewed
Found lots of improved CTor calls, fine.
Found usage of atomic<T> and load/sroe operations, fine.

I am still missing the big picture, Can you point to some background article?
Can we have a Jitsi call where you explain how you are doing this?
What _must_ be tested before this can be merged?

2021-11-14 18:05 UTC, matthiakl commented
> Uhm, how Do I activate the TSAN?

You need  to run cmake with  `-DOPTION_ASAN=OFF -DOPTION_TSAN=ON` 

Basically I looked which variables were accessed from multiple threads as reported by tsan. Then I tried to protect the access by making it atomic.

2021-11-14 18:28 UTC, hessenfarmer commented
@matthiakl  although I really don't understand what is necessary neither what you did here I got the impression this might help with the task of https://github.com/widelands/widelands/pull/5013.
I really got stuck there. maybe you might have a look once this had been merged

2021-11-15 06:50 UTC, klaus-halfmann commented
OK, trying `/compile.sh --debug --no-asan -DOPTION_TSAN=ON `

Do ASAN and TSAN not work together or would it be just to slow?

2021-11-15 06:59 UTC, klaus-halfmann approved these changes
OK, this _is_ really slow. But I got no TSAN Warnings on startup,
Continuing a game gave me however lots of them, where can we collect these?

2021-11-15 16:59 UTC, matthiakl commented
> I really got stuck there. maybe you might have a look once this had been merged

I will take a look into it and see if I can help.

> Do ASAN and TSAN not work together or would it be just to slow?

No, they cannot be enabled together (at least on gcc) and yes they both slow down execution considerably.

> OK, this is really slow. But I got no TSAN Warnings on startup,

That's good. On master you will get some warnings. Since you are on Mac, I suspect you have another audio library than libpulse which created some warnings on my system.

> Continuing a game gave me however lots of them, where can we collect these?

We should open a new issue, to resolve remaining issues in a future branch.

2021-11-15 17:06 UTC, Noordfrees reviewed
Please use spaces instead of tabs for indentation in CMake files for consistency. And the compile.sh short option should be kept to 1 character, it doesn't need to be related to the long name if we're running out of letters.

2021-11-15 21:24 UTC, matthiakl commented
> Please use spaces instead of tabs for indentation in CMake files for consistency

Stupid editor settings…
I chose `m` now as short option (multithreading) for thread sanitizer.
The linkage with atomic is a bit weird: clang on linux needs it explicitly while on mac it is builtin. It should compile now on all platforms.

2021-11-16 08:20 UTC, klaus-halfmann commented
Used new compile script, fine.
Still OK for me. created the expectable followup Issues: #5119 #5120

2021-11-16 08:26 UTC, Noordfrees approved these changes

2021-11-16 14:57 UTC, merged