Fix workarea display bug
widelands/widelands pull request #5371
Opened 2022-04-23 09:58 UTC by matthiakl

Fixes #4881 
- No duplicate workareas
- Hide unowned workareas

2022-04-23 09:59 UTC, matthiakl commented on src/wui/fieldaction.cc
> +							}
Only refactored for better readability. No logic changes.

2022-04-23 13:48 UTC, Noordfrees requested changes
This removes too many workareas. When placing a building with a conquer radius we also want to highlight all intersecting workareas of enemy buildings with conquer radii, and this change would disable this feature.

2022-04-23 17:38 UTC, matthiakl commented
Ah, ok. I didn't know it for military site. On a second look the ownership check was present for production sites, but missing for construction sites.

2022-05-01 13:04 UTC, Noordfrees reviewed
Now when I place the constructionsite for a lumberjack's hut the adjacent constructionsite for a ranger's hut is not highlighted

2022-05-01 14:11 UTC, matthiakl commented
> Now when I place the constructionsite for a lumberjack's hut the adjacent constructionsite for a ranger's hut is not highlighted

Fixed. clang-tidy reported an equal condition, but there was one small important difference.

2022-05-01 14:16 UTC, Noordfrees approved these changes

2022-05-01 18:09 UTC, merged

2022-05-01 20:19 UTC, matthiakl commented
Thanks for the review :)