Replace directory with animation_directory in animations
widelands/widelands pull request #5519
Opened 2022-08-20 11:59 UTC by Veracion

Fixes #5411 
For v1.2.

- [ ] Replace `directory` with `animation_directory (Exceptions: Frisian soldier, immovables with shared sprites directory)
- [ ] Remove `basename` in touched files where it's unnecessary
- [ ] Remove outdated TODO comments (see linked issue)
- [ ] Coverage in test suite

2022-08-20 19:27 UTC, Veracion commented
For the tests, there is already `test_animations.lua`. It does not cover `directory` yet, however. Should I...
a. move one of the used animations' to a subfolder and add a `directory` to its definition?
b. extend the test by a new unit using only `directory` (without an `animation_directory` entry)?
With the latter one additionally guarding against a potential regression of `animation_directory` actually becoming mandatory. First one I already tried and is rather easy to realize.

2022-11-06 19:57 UTC, hessenfarmer commented on regression_test.py
> -import platform
Please explain this deletion

2022-11-06 20:04 UTC, hessenfarmer commented
> For the tests, there is already `test_animations.lua`. It does not cover `directory` yet, however. Should I... a. move one of the used animations' to a subfolder and add a `directory` to its definition? b. extend the test by a new unit using only `directory` (without an `animation_directory` entry)? With the latter one additionally guarding against a potential regression of `animation_directory` actually becoming mandatory.
> 
> For now I've done the first one, which was rather easy to realize.

Although I think the solution should work, the safer one would be b) imho (@Noordfrees ). please change accordingly.

2022-11-16 21:43 UTC, hessenfarmer commented
Hello @Veracion would you still like to work on this?

2022-12-09 12:13 UTC, Veracion commented on regression_test.py
> -import platform
Import was unused

2022-12-09 12:22 UTC, Veracion commented
@hessenfarmer 
> Although I think the solution should work, the safer one would be b) imho (@ Noordfrees ). please change accordingly.

Will do, option a didn't work anyways. Test fails because if an `animation_directory` exists for a file, it is always preferred over an individual `directory`.

> would you still like to work on this?

Yes, I'd like to. Will get to it this month.

2022-12-09 15:34 UTC, hessenfarmer commented
> > would you still like to work on this?
> 
> Yes, I'd like to. Will get to it this month.

I am glad to hear that

2023-01-17 16:43 UTC, hessenfarmer commented
@Veracion any updates on the schedule for this?

2023-01-26 18:26 UTC, Veracion commented
Have resolved the merge conflicts and undone the non-working test changes.

Still struggling with the test_animations, progress isn't quite fast. If anyone wants to help or do that part instead I wouldn't mind. Otherwise in the next few weeks, if I get it running.

2023-01-31 15:12 UTC, hessenfarmer commented
you might try the most simplistic solution just to duplicate the 2 units in the folder tribes and switch them from animation_directory syntax to directory syntax. just add a "_dir" to their internal name (e.g. barbarians_file_animation_dir) in the init.lua file and the register.lua file.  
duplicate animations_test.lua as well with an appropriate name and use the new names (including the _dir appendix) in the new test file.

2023-02-22 09:28 UTC, hessenfarmer commented
Changes look good. if testsuite goes green I'll approve and merge.
Thanks for your contribution.
@Veracion as for every new contributor: how do you wish to be listed in our credits? nickname? realname? or both?

2023-02-22 13:05 UTC, Veracion commented
Thank you for the review & patience, hessenfarmer. Glad to have got this done in time for 1.2.

As for the credits, I'd like the nickname only please.

2023-03-09 10:07 UTC, hessenfarmer requested changes
found the error for the testsuite I believe

2023-03-09 10:07 UTC, hessenfarmer commented on test/maps/plain.wmf/scripting/tribes/legacy_file_animation_dir/init.lua
> +   icon = dirname .. "menu.png",
```suggestion
   icon = dirname .. "../file_animation" .. "menu.png",
```

2023-03-09 10:07 UTC, hessenfarmer commented on test/maps/plain.wmf/scripting/tribes/legacy_spritesheet_animation_dir/init.lua
> +   icon = dirname .. "menu.png",
```suggestion
   icon = dirname.. "../spritesheet_animation" .. "menu.png",
```

2023-03-09 12:09 UTC, hessenfarmer commented
@Veracion please consider commiting my suggestions as I don't want to commit to your fork (not sure whether i am allowed to anyway)

2023-03-10 20:46 UTC, Veracion commented
gotcha, am on it

2023-03-10 23:50 UTC, hessenfarmer approved these changes
LGTM now

2023-03-11 10:30 UTC, merged