Fix sleep times in production buildings
widelands/widelands pull request #5778
Opened 2023-02-13 12:45 UTC by gpalino

Continuation of https://github.com/widelands/widelands/pull/5768
Discussion in https://www.widelands.org/forum/topic/5729/

Now all production sites with return=skipped should have fixed sleep time.
Updated related performance help texts.

2023-02-13 19:43 UTC, hessenfarmer requested changes
some small comments inline

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/buildings/productionsites/empire/marblemine_deep/init.lua
> +            "sleep=duration:28s",
```suggestion
            "sleep=duration:29s",
```
makes a total of 96 which is dividable by 2 and 3

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/initialization/empire/units.lua
> +            },
I believe the curly brackets used around the purpose part are superfluous here, so maybe you might remove them, to fix it in drive by

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/initialization/empire/units.lua
> +            performance = pgettext("empire_building", "If the food supply is steady, this mine can produce marble in %s and granite in %s on average."):bformat(format_seconds(19), format_seconds(19))
as we produce 4 granite and 4 marble each full cycle the average time for 1 of them is 38 not 19

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/initialization/empire/units.lua
> +            performance = pgettext("empire_building", "If the food supply is steady, this mine can produce marble in %s and granite in %s on average."):bformat(format_seconds(19), format_seconds(19))
here we have an average of total time divided by 3 for marble and total time divided by 2 for granite.
as the values are different we should have numerized placeholders here.

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/initialization/frisians/units.lua
> +            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one sword in %s on average and one helmet in %s on average."):bformat(for
I think it might be worth the pain to distinguish the swords

2023-02-13 19:43 UTC, hessenfarmer commented on data/tribes/initialization/frisians/units.lua
> +            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one sword in %s on average and one helmet in %s on average."):bformat(for
same here please distinguish the swords

2023-02-14 06:59 UTC, gpalino commented on data/tribes/initialization/frisians/units.lua
> +            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one sword in %s on average and one helmet in %s on average."):bformat(for
Which formulation do you prefer?
... this building can produce short sword or long sword in %s on average and helmet in %s on average.
... this building can produce basic type of sword (short or long) in %s on average and helmet in %s on average.

2023-02-14 13:32 UTC, hessenfarmer commented on data/tribes/initialization/empire/units.lua
> +            performance = pgettext("empire_building", "If the food supply is steady, this mine can produce marble in %s and granite in %s on average."):bformat(format_seconds(32), format_seconds(46))
96 / 2 = 48 ;-)

2023-02-14 13:37 UTC, hessenfarmer commented on data/tribes/initialization/frisians/units.lua
> +            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one sword in %s on average and one helmet in %s on average."):bformat(for
```suggestion
            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one short sword in %s on average, one long sword in %s on average and one helmet in %s on average."):bformat(format_minutes_seconds(4, 14), format_minutes_seconds(2, 7), format_minutes_seconds(4, 14))
```

2023-02-15 08:44 UTC, hessenfarmer commented on data/tribes/initialization/frisians/units.lua
> +            performance = pgettext("frisians_building", "If all needed wares are delivered in time, this building can produce one sword in %s on average and one helmet in %s on average."):bformat(for
see suggestion below

2023-02-17 00:07 UTC, gpalino commented
I understood your point for buildings which produce different kinds of wares. I was focusing on specific wares (like what happens if economy needs only this ware).

So in current state, there are more calculations broken, like Frisian Mead Brewery and Honey Bread Bakery, both Barbarian Inns. I plan to fix this next days.

From the user perspective, I would like to have time information for both cases
- all output wares are needed in economy
- only one of wares is needed in economy
This is used e.g. in Empire Inn help text. But this approach needs bigger rework of help texts, and maybe recalculation of sleep times to have everything dividable.

One additional question - I've noticed change of placeholders in commit 3110806, to the format %1$s %2$s instead of pure %s.
Is this desired for all strings with multiple %s placeholders?

2023-02-17 07:59 UTC, hessenfarmer commented
> I understood your point for buildings which produce different kinds of wares. I was focusing on specific wares (like what happens if economy needs only this ware).
> 
> So in current state, there are more calculations broken, like Frisian Mead Brewery and Honey Bread Bakery, both Barbarian Inns. I plan to fix this next days.

thanks a lot and take your time. I will be afk for a few days anyway.

> 
> From the user perspective, I would like to have time information for both cases
> 
>     * all output wares are needed in economy
> 
>     * only one of wares is needed in economy
>       This is used e.g. in Empire Inn help text. But this approach needs bigger rework of help texts, and maybe recalculation of sleep times to have everything dividable.

well we could have the one ware as well, but first we should calculate all things like the full cycle is running.   

> 
> 
> One additional question - I've noticed change of placeholders in commit [3110806](https://github.com/widelands/widelands/commit/3110806e0d27038e57b5a364bbfabda04852b1f7), to the format %1$s %2$s instead of pure %s. Is this desired for all strings with multiple %s placeholders?    
   
yes please. reason is that in some languages the order needs to be reversed as they are read from right to left.

2023-02-17 09:19 UTC, tothxa commented
> > From the user perspective, I would like to have time information for both cases
> > ```
> > * all output wares are needed in economy
> > 
> > * only one of wares is needed in economy
> >   This is used e.g. in Empire Inn help text. But this approach needs bigger rework of help texts, and maybe recalculation of sleep times to have everything dividable.
> > ```
> 
> well we could have the one ware as well, but first we should calculate all things like the full cycle is running.

In either case, the wording should clearly reflect what's happening. For full cycle, I suggest something like:

"If all wares are needed by the economy and it is fully supplied, then this building will produce on average one `<ware1>` in `<time1>`, then one `<ware2>` in `<time2>`, … and finally one `<ware[n]>` in `<time[n]>`, for a total of `<total_time>`."

I'm not sure how you calculate with the sleep time between cycles, but in this case it should probably not be spread over the wares, but included directly after `ware[n]`, like "then it sleeps for `<sleeptime>`, for a total…"

2023-03-05 16:11 UTC, hessenfarmer commented
ok so from the conversation above this would be ok to reflect a full cycle everywhere.     
From my perspective we can have it now.     
for the implementation of having both infos for full cycle and each ware we might do this in a new PR, unless @gpalino wants do to it in this one.
I like the suggestion of @tothxa for the texts in this case with some small changes: "When this building is fully supplied, production of <ware_a> takes <time_1> and <ware_b> takes <time_b>. If  all wares are needed this results in a total time of <time_tot> for <x> <wares_a> and <y> <wares_b>. 

so @gpalino please advice whether to make the changes here or in a new PR

2023-03-06 06:19 UTC, gpalino commented
> ok so from the conversation above this would be ok to reflect a full cycle everywhere. From my perspective we can have it now. for the implementation of having both infos for full cycle and each ware we might do this in a new PR, unless @gpalino wants do to it in this one. I like the suggestion of @tothxa for the texts in this case with some small changes: "When this building is fully supplied, production of <ware_a> takes <time_1> and <ware_b> takes <time_b>. If all wares are needed this results in a total time of <time_tot> for <wares_a> and <wares_b>.
> 
> so @gpalino please advice whether to make the changes here or in a new PR

Let's make changes in new PR and finalize this one, I am finished here.

2023-03-06 20:21 UTC, hessenfarmer approved these changes
thanks for the work

2023-03-06 20:22 UTC, hessenfarmer commented
@gpalino thanks for the patience. how do you like to be credited: Nickname, realname or both

2023-03-06 20:37 UTC, gpalino commented
> @gpalino thanks for the patience. how do you like to be credited: Nickname, realname or both

Realname is OK.

2023-03-07 00:57 UTC, merged