5667 player end status fix
widelands/widelands pull request #5823
Opened 2023-03-23 09:35 UTC by hessenfarmer

Please fill out the relevant sections below and delete the rest.

**Type of change**
Bugfix

**Issue(s) closed**
Fixes #5667 
Fixes #5809

**How it works**
the players end status table is now always as big as kMaxPlayers (16) to make it possible to address it by playernumber as introduced in #5604 whic was the culprit for the bug

**Possible regressions**
everything with regard to winconditions and game summary.

2023-03-25 16:25 UTC, tothxa requested changes

2023-03-25 16:25 UTC, tothxa commented on src/network/gamehost.cc
> +	   d->game->player_manager()->get_player_end_status(playernum);
I think this shouldn't have been changed. You don't change the meaning of it anywhere else. (I remember from reviewing #5604 that there are 2 kinds of player numbers, one is 0 based, the other is 1 based, and this is a conversion between them)

I ran a test, and it regresses on #5604 in a way that I believe is because of this: if host is player 1 and it loses, then the host can change the speed, but player 2 cannot. If host is player 2, then both player 1 and 2 can still change the speed after host / player 2 loses.

I've checked, and it turns out that `players_end_status_` is actually always indexed by `player - 1`.

2023-03-25 16:25 UTC, tothxa commented on src/network/gamehost.cc
> +	   d->game->player_manager()->get_player_end_status(playernum);
Yes, tested and restores correct behaviour.

```suggestion
	   d->game->player_manager()->get_player_end_status(playernum + 1);
```

2023-03-25 20:11 UTC, tothxa commented
Rest looks OK, fix confirmed with savegame from #5809.

2023-03-26 20:55 UTC, hessenfarmer commented
i have teste some changes but it seems they were wild guesses. I am not sure yet what causes the crashes.

2023-03-26 21:59 UTC, tothxa commented
I think this should be solved in `playersmanager` only. I'll try turning `players_end_status_` into a `std::map` to handle non-continuous player numbers…

2023-03-27 06:48 UTC, hessenfarmer commented
> I think this should be solved in `playersmanager` only. I'll try turning `players_end_status_` into a `std::map` to handle non-continuous player numbers…    
   
From what I understand it is not the call to players_end_status that is crashing. it is the indexed call to the players table in game summary.cc, which has its own index, that is causing it.

2023-03-27 09:22 UTC, tothxa commented
> From what I understand it is not the call to players_end_status that is crashing. it is the indexed call to the players table in game summary.cc, which has its own index, that is causing it.

Yes, you're right. After some experimentation I believe this is a separate bug in `GameSummaryScreen::fill_data()`, also introduced by #5604. I thought I had an idea how to solve it, but it failed, so now I'm quite confused what might cause it. I'll do some deeper debugging on it.

2023-03-27 09:43 UTC, hessenfarmer commented
> > From what I understand it is not the call to players_end_status that is crashing. it is the indexed call to the players table in game summary.cc, which has its own index, that is causing it.
> 
> Yes, you're right. After some experimentation I believe this is a separate bug in `GameSummaryScreen::fill_data()`, also introduced by #5604. I thought I had an idea how to solve it, but it failed, so now I'm quite confused what might cause it. I'll do some deeper debugging on it.

I will try to do so as well tonight

2023-03-27 13:52 UTC, tothxa commented
The problem is that `players_table_` treats the index as if it was the player number in `player_selected()` and I believe also in `compare_status()`. The problem I found in `fill_data()` is also real, we need to keep track of assigned indexes separately from the player number used in the iteration. So that mapping needs to be stored too. I'm not sure whether we can do it in the table itself, or we need to create a separate vector or map for it. Actually it may make sense to do it right in players manager (maybe it already exists?), and use it everywhere for end statuses and possibly other uses.

2023-03-27 18:22 UTC, tothxa commented
See https://github.com/widelands/widelands/pull/5826#issuecomment-1485557381 and https://github.com/widelands/widelands/pull/5826#issuecomment-1485629593:

There are more places where player numbers are iterated only up to number of players in the game, so maybe it would be best to revert https://github.com/widelands/widelands/commit/2a27e73cf68a2394d18649112f35f7bddc909300 and do https://github.com/widelands/widelands/pull/5604#pullrequestreview-1169102400 (with map instead of vector :) but at this point I'm not sure which is easier: untangle https://github.com/widelands/widelands/pull/5604 or hunt down all downstreams that need updating.

2023-03-27 20:25 UTC, closed without merging