win condition wood_gnome can have several winners
widelands/widelands pull request #5952
Opened 2023-06-22 13:09 UTC by SimonHeimberg

In win condition wood_gnome, all players with maximum points win the game. (In case they have the same points at the end by chance.) The message still only lists one of them.
Teams are still not supported.

**Type of change**
partial Bugfix

**Related issue(s)**
improves #3129

2023-06-25 12:21 UTC, hessenfarmer requested changes
one typo inline.
please fix the messages as well, as currently only the first entry of the sorted table will be mentioned in the message.  
I was not aware that we do not have a teams option for woodgnome so it would be good to fix that as well for this (but this is not mandatory for this PR)

2023-06-25 12:21 UTC, hessenfarmer commented on data/scripting/win_conditions/wood_gnome.lua
> +         points[i][1]:send_to_inbox(end_msg.title, privmsg)
```suggestion
         points[i][1]:send_to_inbox(end_msgs.title, privmsg)
```

2023-06-29 08:45 UTC, SimonHeimberg commented
> please fix the messages as well, as currently only the first entry of the sorted table will be mentioned in the message. I was not aware that we do not have a teams option for woodgnome so it would be good to fix that as well for this (but this is not mandatory for this PR)

How do you suggest to to fix the message? Remove mentioning the winner since wood_gnome is the only win condition doing this?

2023-07-01 12:32 UTC, hessenfarmer commented
skipping the message would be the easy fix, collecting all winning players in a table in another iteration of the points table and concatenating their names in the message (use of ngettext would be required) would be the cherry on the cake

2023-07-04 19:52 UTC, hessenfarmer approved these changes

2023-07-04 19:54 UTC, hessenfarmer commented
I can live with that remaining TODO.  
So I will merge when CI is green, unless you tell me you will fix the TODO right here in this PR.    
How do you want to be credited (name, nickname, both)?

2023-07-04 20:27 UTC, SimonHeimberg commented
> I can live with that remaining TODO. So I will merge when CI is green, unless you tell me you will fix the TODO right here in this PR. How do you want to be credited (name, nickname, both)?

only nickname aDiscoverer is fine

2023-07-05 07:05 UTC, merged