extend documentation about attributes of units
widelands/widelands pull request #6195
Opened 2023-10-18 19:47 UTC by SimonHeimberg

**Type of change**
Doc enhancement

**Issue(s) closed**
improves #4744

**Changed behavior**
The documentation for lua api only mentions has_attribute() for ImmovableDescription. But it exists for all MapObjectDescriptions. It will return false for all types except of ImmovableDescription and critters.
The documentation about writing units tells attributes can be set, but does not mention they do not work for all units.

2023-11-14 22:00 UTC, hessenfarmer requested changes
I believe we need a refactoring here rather then a documentation change

2023-11-14 22:00 UTC, hessenfarmer commented on doc/sphinx/source/lua_tribes_units.rst.org
> +Free attributes are only supported for immovables (and critters).
I would rather add a part to the sentence above like "Additionally to its normal attributes (link to the documentation of the mapObject attribute below), every unit defined by an add-on ....

2023-11-14 22:00 UTC, hessenfarmer commented on doc/sphinx/source/lua_world_units.rst.org
> +Free attributes are only supported for immovables and critters.
same as for tribes units

2023-11-14 22:00 UTC, hessenfarmer commented on src/scripting/lua_map.cc
> +      Note: This method does exist for all MapObjects, but it only gets initialised for this class
It exists as it is already defined for the base class.  From my perspective this is an unneeded duplication imho and should be harmonized into the base class (i.e. merging the error reporting part into the base class definition)

2023-11-25 21:26 UTC, SimonHeimberg commented on src/scripting/lua_map.cc
> +      Note: This method does exist for all MapObjects, but it only gets initialised for this class
Actually this are two different object hierarchies. And I added the comment to the wrong function.
This one is `LuaImmovableDescription`, the other object is `MapObject` (which do have a description). They do not inherit from each other (a MapObject contains a xxDescription)

2023-11-25 21:34 UTC, SimonHeimberg commented
> I believe we need a refactoring here rather then a documentation change

What kind of a refactoring?
- Should all MapObjects read attributes (from "register.lua")?
  Attributes are passed to the constructor of two objects (Critters and Immovables) in
https://github.com/widelands/widelands/blob/aac51a3baa3dca12d6c6c8017b629bd6c7a4534b/src/logic/map_objects/descriptions.cc#L431
  , to pass it to all Subclasses of MapObjects would be quite some work. (Maybe there is a simpler way than to add it to every constructor.)
- Unify the methods named `has_attribute()`?
  They are in different class hierarchies.
- ...?

2023-11-26 19:51 UTC, hessenfarmer commented on src/scripting/lua_map.cc
> +      Note: This method does exist for all MapObjects, but it only gets initialised for this class
> Actually this are two different object hierarchies. And I added the comment to the wrong function. This one is `LuaImmovableDescription`, the other class is `MapObject`. They do not inherit from each other (a MapObject contains a xxDescription)

The base class for immovables and critters is mapobject. So immovables as well as critters inherit from mapobject.   
Both lua methods use the same c++ funtion from mapobject description.  so in c++ it is only defined in mapobject description and my proposal was to do it the same way in lua.

2023-11-26 20:09 UTC, hessenfarmer commented
> > I believe we need a refactoring here rather then a documentation change
> 
> What kind of a refactoring?
> 
>     * Should all MapObjects read attributes (from their "register.lua")?
>       Attributes are passed to the constructor of two objects (Critters and Immovables) in
>       https://github.com/widelands/widelands/blob/aac51a3baa3dca12d6c6c8017b629bd6c7a4534b/src/logic/map_objects/descriptions.cc#L431
>       
>       , to pass it to all Subclasses of MapObjects would be quite some work. (Maybe there is a simpler way than to add it to every constructor.)     
    
as you already wrote in your proposed change each mapobject has it, but it is only initialized for immovables and critters.  so no need to change anything there.  
   
> 
>     * Unify the methods named `has_attribute()`?
>       They are in different class hierarchies.
> 
>     * Should `has_attribute()` of `LuaImmovableDescription` be moved to a parent class? (Probably confusing, as only Immovable and Critter support loading the attribute values.)
> 
>     * ...?
   
I thought of determining whether we have the description already or have the object as in the end we return the value from the description.    

but we could keep it for the moment being and just shift the text changes to the correct point

2023-11-30 22:44 UTC, hessenfarmer commented on doc/sphinx/source/lua_tribes_units.rst.org
> +Additionaly to its normal attributes (:method:`MapObject.has_attribute`), every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_
sorry i did not recognize the context in this file in the first case. As the normal attributes asre explained above we could simply skip the reference to make the ci happy
```suggestion
Additionaly to its normal attributes, every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_exists``. This attribute determines how the engine proceeds if a description of the same name has already been registered. Units not contained in an add-on may not use these attributes.
```

2023-11-30 22:45 UTC, hessenfarmer commented on doc/sphinx/source/lua_world_units.rst.org
> +Additionaly to its normal attributes (:method:`MapObject.has_attribute`), every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_
same here
```suggestion
Additionaly to its normal attributes, every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_exists``. This attribute determines how the engine proceeds if a description of the same name has already been registered. Units not contained in an add-on may not use these attributes.
```

2023-12-01 16:27 UTC, SimonHeimberg commented on doc/sphinx/source/lua_tribes_units.rst.org
> +Additionaly to its normal attributes (:method:`MapObject.has_attribute`), every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_
But then we do not have mentioned that the normal attributes are only supported for Immovables and Critters. (Actually I prepared a follow up pr which initializes the attributes for all customizable map objects. Then in does not matter anymore.)
By the way, the doc check [complains about :method:](/widelands/widelands/actions/runs/7048322366/job/19184229800?pr=6195), which does not need to be resolved if we drop the reference.

2023-12-01 18:10 UTC, SimonHeimberg commented
> "Additionaly to" → "In addition to" (2×)
> 

Sounds good. Will do when the other change is clear.

> In the note, please use
> 
> ```
> .. note::
> ```
> 
> and
> 
> ```
> :const:`false`
> ```

After looking at the changed files, I found those in src/scripting/lua_map.cc and improved it.

2023-12-01 20:18 UTC, hessenfarmer commented on doc/sphinx/source/lua_tribes_units.rst.org
> +Additionaly to its normal attributes (:method:`MapObject.has_attribute`), every unit defined by an add-on needs to define exactly one of the special attributes ``__skip_if_exists`` or ``__replace_if_
that is correct. How about adding this information after line 14 of this file (line 178 in the other file) where attributes are first mentioned.  
the complain of the ci doc check was wha i was sugesting to remove the reference.

2023-12-04 20:08 UTC, hessenfarmer approved these changes
thanks for fixing it it should be 100% clear now for everybody.

2023-12-04 20:11 UTC, hessenfarmer commented
@bunnybot update

2023-12-04 20:25 UTC, hessenfarmer commented
@bunnybot merge

2023-12-04 22:03 UTC, closed without merging