Fix documentation of the objectives lua interface
widelands/widelands pull request #6274
Opened 2023-12-16 22:12 UTC by bunnybot

<img align='left' src='https://codeberg.org/avatars/593dc43e2444c25db9481960e5b693ab' alt='tothxa' height='48' />*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4613)*
*Created on Sat Dec 16 23:05:39 CET 2023 by **Tóth András (tothxa)***

---

**Type of change**
Documentation fix

**Issue(s) closed**
Re #6271 (quick minimal fix)

**Possible regressions**
n/a

2023-12-21 18:38 UTC, SimonHeimberg commented on src/scripting/lua_game.cc
> +         by all players, so it's not possible to have different objectives for different
or ...`, so just use it for the interactive player.`

2023-12-21 18:41 UTC, SimonHeimberg commented
Some sentences can be discussed, but
I am totally for this. 👍

2023-12-26 19:14 UTC, hessenfarmer requested changes
some fin al remarks

2023-12-26 19:14 UTC, hessenfarmer commented on src/scripting/lua_game.cc
> +   This represents an Objective, a goal for the player in the scenario. This is
well in fact objectives do not belong only to scenarios, but each wincondition sets an objective and a map can set an objective as well. so I believe game was correct here

2023-12-26 19:14 UTC, hessenfarmer commented on src/scripting/lua_game.cc
> +      .. note:: In spite of accessing them through :class:`~wl.game.Player`, Objectives
```suggestion
      .. note:: Although objectives are accesible through :class:`~wl.game.Player`, Objectives
```

2023-12-26 19:14 UTC, hessenfarmer commented on src/scripting/lua_game.cc
> +   This represents an Objective, a goal for the player in the scenario. This is
please add plural instead of singular ion line 1257 below : i.e. hide it from the users

mabe the same in line 1350 as well

2023-12-27 01:30 UTC, tothxa commented
I updated the PR branch on codeberg according to the suggestions, but it looks like the mirror bot has problems again.

2024-01-05 22:53 UTC, hessenfarmer approved these changes
lgtm now

2024-01-05 22:57 UTC, hessenfarmer commented
@bunnybot update

2024-01-05 22:58 UTC, hessenfarmer commented
@bunnybot merge

2024-01-05 23:49 UTC, closed without merging