Musicplayer
widelands/widelands pull request #6585
Opened 2024-12-09 00:19 UTC by andersand

### Type of Change
New feature

### New Behavior
This adds a music player in the sound options, with a simple playlist and option to shuffle playback. The settings are persisted using the existing config routine.

### How it Works
Should be self explanatory, but refer to my post in the dev forums.

### Possible Regressions
Maybe, as I have not tested extensively.

2024-12-09 21:14 UTC, hessenfarmer commented
just a short tip: 
first fix the other checks afterwards clang_tidy
and make sur from the clang_tidy documents that you really undertand each issue.

2024-12-09 21:51 UTC, andersand commented
> just a short tip: first fix the other checks afterwards clang_tidy and make sur from the clang_tidy documents that you really undertand each issue.

Thanks for the tips. The remaining clang issues I have to resign for tonight, if someone knows a solution please advise. I made some attempts but either they end up not compiling or a runtime error, or even like the one where it says to use = default contradicts another where I have to use explicit for the one-arg ctor. I had to add the no-arg ctor since I stopped using pointers for the Song struct.

The one clang complains about that says the SDL function is not defined, I don't get. I even added `#include <SDL_mixer.h>` to the impl as well as the header files. 
I also tried to use different ways to assign the char* to a std::string but which ever way I try clang is not happy, regardless of that it appears to work well in the game...

2024-12-09 22:01 UTC, hessenfarmer commented
this is normal. making it work is only the first step. making it codesafe is much more difficult. However be assured this rigorous checks safed us quite a lot of times.

2024-12-10 15:50 UTC, andersand commented
> [<img alt="tothxa" height="48" src="https://camo.githubusercontent.com/12c4199cc6c607a28ee64a11a49ff4a858ff476b42fd147a3a7adc81c140a7e0/68747470733a2f2f636f6465626572672e6f72672f617661746172732f3539336463343365323434346332356462393438313936306535623639336162">](https://codeberg.org/tothxa)_[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-2506411)_ _On Tue Dec 10 00:01:57 CET 2024, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:_
> 
> > The one clang complains about that says the SDL function is not defined, I don't get. I even added `#include <SDL_mixer.h>` to the impl as well as the header files.
> 
> `Mix_GetMusicTitle()` is a somewhat new addition to SDL, it may be that the SDL version on the runner doesn't have it. I've just checked: it was added in SDL-mixer 2.6.0, which was released in July 2022, while the clang-tidy job is run on ubuntu-22.04. So it looks like you have to prepare fallback code for old SDL versions (IMO the filename is sufficient for this, you shouldn't go hunting for new dependencies again), because ubuntu-22.04 will be supported for at least 2 more years.

I'm not familiar with "preparing fallback code" - what do I have to do?

2024-12-10 19:51 UTC, andersand commented
Looks like that was it for the pre-build checks. Thank you for the help :smiley: 

It also seems to compile, but unfortunately there's some more failing testsuites too.

There are also a few loose ends in the conversations, I'm waiting for Nordfriese to reply to those.

For the testing there is one thing that you will notice though. I couldn't find a simple way to make sure the current track title is in sync with what's playing if you change song while the music player is still open. to hear it. I was considering using a custom SDL event, but it seems they should be handled only in one place, so that wouldn't work. If you have any suggestions I'd love to hear about it.

2024-12-10 20:55 UTC, hessenfarmer commented
just in case you did not find the information in the failing logs yet:

```
  Running widelands binary: build/src/widelands --verbose --datadir=/home/runner/work/widelands/widelands/./data --datadir_for_testing=. --homedir=/tmp/widelands_regression_test_0qratsts --nosound --fail-on-lua-error --language=en --editor=test/maps/lua_testsuite.wmf --script=test/maps/lua_testsuite.wmf/scripting/editor_test_lua_in_editor.lua 
  This is Widelands version 1.3~git1 (9cbae5b@HEAD) Debug
  Adding home directory: /tmp/widelands_regression_test_0qratsts
  [00:00:00.000 real] INFO: Set home directory: /tmp/widelands_regression_test_0qratsts
  [00:00:00.000 real] INFO: Set configuration file: /tmp/widelands_regression_test_0qratsts/config
  [00:00:00.000 real] ERROR: [] config:0: RealFSImpl::load: could not open file for reading: /tmp/widelands_regression_test_0qratsts/config
  [00:00:00.002 real] INFO: Adding data directory: /home/runner/work/widelands/widelands/data
  [00:00:00.002 real] INFO: Adding testing directory: /home/runner/work/widelands/widelands
  [00:00:00.168 real] INFO: Setting initializer thread.
  [00:00:00.168 real] INFO: Byte order: little-endian
  MESA: error: ZINK: failed to choose pdev
  glx: failed to create drisw screen
  [00:00:00.297 real] INFO: Graphics: Try to set Videomode 800x600
  [00:00:00.329 real] INFO: Graphics: OpenGL: Version "4.5 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.3"
  [00:00:00.330 real] INFO: Graphics: SDL_GL_RED_SIZE is 8
  [00:00:00.330 real] INFO: Graphics: SDL_GL_GREEN_SIZE is 8
  [00:00:00.330 real] INFO: Graphics: SDL_GL_BLUE_SIZE is 8
  [00:00:00.330 real] INFO: Graphics: SDL_GL_ALPHA_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_BUFFER_SIZE is 24
  [00:00:00.330 real] INFO: Graphics: SDL_GL_DOUBLEBUFFER is 1
  [00:00:00.330 real] INFO: Graphics: SDL_GL_DEPTH_SIZE is 32
  [00:00:00.330 real] INFO: Graphics: SDL_GL_STENCIL_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
  [00:00:00.330 real] INFO: Graphics: SDL_GL_STEREO is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
  [00:00:00.331 real] INFO: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
  [00:00:00.331 real] INFO: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
  [00:00:00.331 real] INFO: Graphics: SDL_GL_CONTEXT_FLAGS is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
  [00:00:00.331 real] INFO: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
  [00:00:00.331 real] INFO: Graphics: OpenGL: Double buffering enabled
  [00:00:00.331 real] INFO: Graphics: OpenGL: Max texture size: 16384
  [00:00:00.331 real] INFO: Graphics: OpenGL: ShadingLanguage: "4.50"
  [00:00:00.336 real] INFO: **** GRAPHICS REPORT ****
  [00:00:00.336 real] INFO: VIDEO DRIVER GLVND x11
  [00:00:00.336 real] INFO: Display #0: 800x600 @ 0hz SDL_PIXELFORMAT_RGB888
  [00:00:00.336 real] INFO: **** END GRAPHICS REPORT ****
  [00:00:00.336 real] INFO: Handled 4 SDL window events at start up
  [00:00:00.351 real] INFO: Font handler created
  [00:00:00.395 real] INFO: Style Manager: Reading style templates took 44ms
  [00:00:00.417 real] INFO: Loaded default styles
  [00:00:00.595 real] INFO: Splash screen shown
  [00:00:00.595 real] INFO: Rebuilding texture atlas
  [00:00:02.561 real] INFO: Texture atlas rebuilt
  [00:00:02.561 real] INFO: Cleaning up temporary files
  [00:00:02.565 real] INFO: Loading songsets
  [00:00:02.565 real] INFO: Initializing Add-Ons
  [00:00:02.566 real] INFO: Done initializing Add-Ons
  AddressSanitizer:DEADLYSIGNAL
  =================================================================
  ==56567==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x564152b33032 bp 0x7ffc8e0c0910 sp 0x7ffc8e0c08e0 T0)
  ==56567==The signal is caused by a READ memory access.
  ==56567==Hint: address points to the zero page.
      #0 0x564152b33032 in __gnu_cxx::__normal_iterator<Section::Value*, std::vector<Section::Value, std::allocator<Section::Value>>>::__normal_iterator(Section::Value* const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_iterator.h:1068:20
      #1 0x564152b2d712 in std::vector<Section::Value, std::allocator<Section::Value>>::begin() /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_vector.h:874:16
      #2 0x564154004cf0 in Section::mark_values() /home/runner/work/widelands/widelands/src/io/profile.cc:288:27
      #3 0x564152256770 in WLApplication::WLApplication(int, char const* const*) /home/runner/work/widelands/widelands/src/wlapplication.cc:545:7
      #4 0x5641522534c3 in WLApplication::get(int, char const**) /home/runner/work/widelands/widelands/src/wlapplication.cc:347:23
      #5 0x564152250b35 in main /home/runner/work/widelands/widelands/src/main.cc:131:26
      #6 0x7ff00f22a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
      #7 0x7ff00f22a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
      #8 0x564152172524 in _start (/home/runner/work/widelands/widelands/build/src/widelands+0xc65524) (BuildId: 2f2cc4f327ed4d87d70bcc0bd836161f63fff93b)
  
  AddressSanitizer can not provide additional info.
  SUMMARY: AddressSanitizer: SEGV /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_iterator.h:1068:20 in __gnu_cxx::__normal_iterator<Section::Value*, std::vector<Section::Value, std::allocator<Section::Value>>>::__normal_iterator(Section::Value* const&)
  ==56567==ABORTING
```

2024-12-10 21:06 UTC, andersand commented
> just in case you did not find the information in the failing logs yet:
> 

I found it, but I haven't solved (or even been able to repro) the issue.

2025-02-08 19:01 UTC, andersand commented
> [<img alt="Nordfriese" height="48" src="https://camo.githubusercontent.com/49a632fc9dcc7c4be06ea72211b35529f0275d6e706568cc129a178aca96ca83/68747470733a2f2f636f6465626572672e6f72672f617661746172732f6134616432663961323530346630353233393764386261383265643438626131">](https://codeberg.org/Nordfriese)_[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-2684356)_ _On Wed Feb 05 19:10:54 CET 2025, [**Benedikt Straub (Nordfriese)**](https://codeberg.org/Nordfriese) **requested changes** on this pull request:_
> 
> I went through the code again and annotated 9 or so more comments. You can disregard any older stale comments in the discussion. Will test again soonish.

Thanks. I've done the edits you proposed.

2025-11-06 16:10 UTC, frankystone commented
@andersand what is the status here?

2025-11-10 21:00 UTC, andersand commented
I've done most of the remaining work tonight. The updating of the dialog is a little more work to get working, if it will even work with think() - but maybe this PR can be accepted even if the dialog is not updating itself? The user can still close and reopen the dialog to see the updated track title. I mean, the sound options dialog is not intended to be a Settlers 2 like jukebox that can be kept open during gameplay anyway? 

Also I don't know why 86/86 tests fail, something must be wrong with the test suite / environment.

2025-11-11 16:42 UTC, andersand commented
> [<img alt="tothxa" height="48" src="https://camo.githubusercontent.com/12c4199cc6c607a28ee64a11a49ff4a858ff476b42fd147a3a7adc81c140a7e0/68747470733a2f2f636f6465626572672e6f72672f617661746172732f3539336463343365323434346332356462393438313936306535623639336162">](https://codeberg.org/tothxa)_[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8212868)_ _On Mon Nov 10 23:24:06 CET 2025, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:_
> 
> The log says it: There's a null pointer dereference soon after add-ons are initialised, most probably the `sec->mark_values()` line, because there's no such section, as there's no config file either in the testsuite. So you need a check:
> 
> ```
> if (sec != nullptr) {
>    sec->mark_values();
> }
> ```

Thanks tothxa, but it seems to still be a nullptr somewhere

2025-11-11 22:26 UTC, andersand commented
Using think to keep the track title updated worked well :+1:  
So now that all the tests are passing also maybe merge the PR?

2025-11-17 22:56 UTC, andersand commented on src/sound/sound_handler.cc
> +				title = _("Untitled");
Ok, I've added the filename fallback.

I think however it would be a good time to give the unnamed songs titles, now that the titles are shown ingame and all. Perhaps that request can be posted to the forums, and we get some nice suggestions for tracks 14 and 21?

2025-11-17 22:58 UTC, andersand commented
> [<img alt="tothxa" height="48" src="https://camo.githubusercontent.com/574a7b714e364c6ba6ba6bf903f8584f91b7ad484b6ee5e85363f982f7a5f229/68747470733a2f2f636f6465626572672e6f72672f617661746172732f3539336463343365323434346332356462393438313936306535623639336162">](https://codeberg.org/tothxa)_[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8310680)_ _On Mon Nov 17 00:07:23 CET 2025, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:_
> 
> bunnybot didn't mirror [this one](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8288663) (regarding the `MusicTrackControl` class):
> 
> Maybe it's asking too much, but I expected that clicking on a song would start playing that song instead of disabling it. Since you wrap the checkbox in a horizontal box anyway, could you please use a simple checkbox without a label, and add the title as a separate textarea (or a button may be easier), and implement starting the song when the title is clicked?

That would be better yes, but I don't know how much work it will be to make it work. Hopefully not too much, since it would be nice to have it. However I'd like to be done soon with this PR that has been going on for a long time.

2025-11-23 22:00 UTC, hessenfarmer commented
with this PR no music is playing in a windows build at all

2025-11-24 13:09 UTC, hessenfarmer commented
I tried to test this on windows but it did not play any music at all. I need to investigate further tonight. could somebody provide me with a screenshot how it should look like

2025-11-24 14:38 UTC, frankystone commented
Looks like the music only plays if you turn "Play my own music" off.

If i turn on this option in the main menus options menu, the in game music options menu does not render properly. The song titles are missing and the scrollbar is somehow at the top border of the area:

<img width="459" height="339" alt="wl_musicplayer" src="https://github.com/user-attachments/assets/2999ed3f-3f83-4480-a3cb-41581a8d31d7" />

Happens also with the default theme.

To be honest: This adds a lot of code without much gain, imho. Mainly because it is just an interface for the 28 in game music titles. Just my personal opinion.

Edit: Maybe i am doing something wrong, but adding the folder `music` containing  `custom_xx.mp3` files in `.widelands/` does not change anything.

2025-11-24 16:03 UTC, frankystone commented
Ok, i did something wrong: The own music files have to start with `custom_00.*`. I have started the numbers with `_01` and that won't load any files.

With those own music files the in game menu of music options renders ok, if one has checked "Use own music" in the main menus sound options.

2025-11-24 20:45 UTC, hessenfarmer requested changes
one major issue inline.
tested it a bit and found one glitch; 
when changing custom to ingame the relevant file list should be loaded. Currently it stays at the original file list.

2025-11-24 20:45 UTC, hessenfarmer commented on src/sound/songset.cc
> +	const std::string& path_basename = "music/" + name_;
we need to use os specific file separators here

2025-11-26 21:48 UTC, andersand commented
Dont know, I’ll try. When om sunday is the deadline?

On Wed 26. Nov 2025 at 18:28, bunnybot ***@***.***> wrote:

> *bunnybot* left a comment (widelands/widelands#6585)
> <https://github.com/widelands/widelands/pull/6585#issuecomment-3582438527>
>
> [image: Nordfriese] <https://codeberg.org/Nordfriese>*Mirrored from
> Codeberg
> <https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8504808>*
> *On Wed Nov 26 18:21:34 CET 2025, Benedikt Straub (Nordfriese)
> <https://codeberg.org/Nordfriese> wrote:*
> ------------------------------
>
> Hi, we plan to have the Winter Time Feature Freeze on this Sunday
> (November 30th) in order to release Widelands 1.3 before Christmas. Do you
> think you could address these last two remaining comments within the next
> days? It would be really cool to have this feature in v1.3 :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/widelands/widelands/pull/6585#issuecomment-3582438527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXY5RUWJ3JWXEMAB3S77L36XPJPAVCNFSM6AAAAACLLEHEK6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTKOBSGQZTQNJSG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-11-27 20:03 UTC, andersand commented
An easy solution to the issue with switching between custom music or the
official music could be to simply remove the checkbox and label from sound
settings when in game. Then you would have to toggle that from main menu
sound settings. That and the Windows path I have time to fix tomorrow. Not
sure how much time I need to make the track list refresh when toggling that
option as I think it would require some refactoring.

On Thu 27. Nov 2025 at 12:04, bunnybot ***@***.***> wrote:

> *bunnybot* left a comment (widelands/widelands#6585)
> <https://github.com/widelands/widelands/pull/6585#issuecomment-3585265162>
>
> [image: Nordfriese] <https://codeberg.org/Nordfriese>*Mirrored from
> Codeberg
> <https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8539695>*
> *On Thu Nov 27 11:54:24 CET 2025, Benedikt Straub (Nordfriese)
> <https://codeberg.org/Nordfriese> wrote:*
> ------------------------------
>
> Dont know, I’ll try. When om sunday is the deadline?
>
> Sunday evening, if it's ready for merging by 22:00 CET that would be
> great. So that it would be already included in Monday's daily builds of
> master for the final two weeks of winter-time-frozen testing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/widelands/widelands/pull/6585#issuecomment-3585265162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXY5XVTYSVOTNY5STMXPT363LDXAVCNFSM6AAAAACLLEHEK6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTKOBVGI3DKMJWGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-11-27 21:25 UTC, hessenfarmer commented on src/sound/songset.cc
> +	const std::string& path_basename = "music/" + name_;
```suggestion
	std::string& path_basename = "music";
	path_basename += FileSystem::file_separator() + name_;
```

this worked for me to fix this.  I agree with @cb/Nordfriese that only fixing this is crucial as it prevents any music in windows at all currently

2025-11-28 22:26 UTC, andersand commented
> [<img alt="Nordfriese" height="48" src="https://camo.githubusercontent.com/85312a60da97e8859f867e4bf434dc462a56ff6429dc7f8a21580992330e2246/68747470733a2f2f636f6465626572672e6f72672f617661746172732f6134616432663961323530346630353233393764386261383265643438626131">](https://codeberg.org/Nordfriese)_[Mirrored from Codeberg](https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8550012)_ _On Thu Nov 27 21:54:26 CET 2025, [**Benedikt Straub (Nordfriese)**](https://codeberg.org/Nordfriese) wrote:_
> 
> I've attached a patch for the songlist update. True, turns out doing this cleanly would be much more involved than I had expected at first, but this hack appears to work. Please check if you like it: [patch](https://codeberg.org/attachments/623e8f32-e19d-40ec-86a3-bcce37dd9f21)
> 
> I'm not really happy with the thought of hiding that checkbox in the game, but if you think it shouldn't be done as proposed in the patch, it would be acceptable as a "quickfix" just to get this feature out for v1.3.

Thanks for the patch. I've tested it and it doesn't seem to break anything, so I think it's good. I also fixed the path as suggested by hessenfarmer.

2025-11-29 09:29 UTC, hessenfarmer approved these changes
everything is fine now from my side. 
thanks for the cool feature.

2025-11-29 16:34 UTC, closed without merging

2025-11-29 23:15 UTC, andersand commented
Thanks, you can just use my nickname.

On Sat, Nov 29, 2025 at 5:29 PM bunnybot ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> [image: Nordfriese] <https://codeberg.org/Nordfriese>*Mirrored from
> Codeberg
> <https://codeberg.org/wl/widelands/pulls/4945#issuecomment-8593209>*
> *On Sat Nov 29 17:24:22 CET 2025, Benedikt Straub (Nordfriese)
> <https://codeberg.org/Nordfriese> approved this pull request:*
>
> Apologies again that the review dragged on for so long and then the rush
> at the end.
> Thank you for your patience, and for the feature :)
>
> How do you want to be credited in the developers list: realname, nickname
> or both?
>
> <@>bunnybot merge
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/widelands/widelands/pull/6585#pullrequestreview-3520752617>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXY5R2DGIYSA6G7EYFED337HCUTAVCNFSM6AAAAACLLEHEK6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZTKMRQG42TENRRG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>